### ISSUE TITLE
Gmovies no longer working

### ISSUE THREAD

**Issue by subby2006** [hexated/cloudstream-extensions-hexated#106]
The gmovies source no longer seems to be working, the option for it no longer appear in movies that used to have it. Bullet train movie for example had 3 to 4 gmovies remux sources but they no longer appear.

**Comment by subby2006** [comment]
On the topic of that, seems like FDMovies is no longer returning sources either

**Comment by hexated** [comment]
> On the topic of that, seems like FDMovies is no longer returning sources either

Gdtot added cloudflare
End of era

**Comment by hexated** [comment]
Fixed now
