### ISSUE TITLE
How to download movie or anime fast 

### ISSUE THREAD

**Issue by Krishna-art-dev** [hexated/cloudstream-extensions-hexated#107]
Cloudstream internal downloader is just too slow , is there any way to download anime or movie fast from cloud stream

**Comment by hexated** [comment]
> Cloudstream internal downloader is just too slow , is there any way to download anime or movie fast from cloud stream 

Use 1dm

https://docs.cloudstream.cf/recapps/

**Comment by Krishna-art-dev** [comment]
Can I have tutorial for it, i just copy video link and try to download it with 1dm and it doesn't work

**Comment by hexated** [comment]
> Can I have tutorial for it, i just copy video link and try to download it with 1dm and it doesn't work 

Join discord server, we can help you in there

**Comment by Krishna-art-dev** [comment]
I am able to download anime from 1dm but from movierulzhd i can't able to download. It just redirect me to movierulzhd website
