### ISSUE TITLE
LOKLOK NO LINKS FOUND

### ISSUE THREAD

**Issue by GlennQu** [hexated/cloudstream-extensions-hexated#108]
Loklok is having no links found again.

**Comment by hexated** [comment]
> Loklok is having no links found again.

I Made a fix but only work with external player

**Comment by GlennQu** [comment]
Thanks. Help us continue to fix it  so it can play using internal player.

**Comment by hexated** [comment]
> Thanks. Help us continue to fix it  so it can play using internal player. 

Update ur app, it should work now
