### ISSUE TITLE
Movierulzhd crashes cloudstream 

### ISSUE THREAD

**Issue by Krishna-art-dev** [hexated/cloudstream-extensions-hexated#109]
I just updated my phone to Android 13 now whenever I try to play any flim with movierulzhd it just crashes.
I am using cloudstream beta 

Tried with other extensions like yugen anime that worked fine

**Comment by Krishna-art-dev** [comment]
this is happening

**Comment by Krishna-art-dev** [comment]
Uploading Record_2023-02-22-14-24-32_480x1068 (1).mp4…

**Comment by hexated** [comment]
> I just updated my phone to Android 13 now whenever I try to play any flim with movierulzhd it just crashes.
> I am using cloudstream beta 
> 
> Tried with other extensions like yugen anime that worked fine 

Can't reproduce

Use pre, clear cache and modify cache in player setting

**Comment by Krishna-art-dev** [comment]
Working now
