### ISSUE TITLE
some problems with Shinobi and Dahmer sources

### ISSUE THREAD

**Issue by subby2006** [hexated/cloudstream-extensions-hexated#110]
Shinobi seems to have added a new direct download link detected screen where it requires you to hit the download button in order to start the stream, maybe some special refferer or header is required as vlc is unable to play the raw link

As for Dahmer, for some reason sora cuts off part of the link, making the link invalid, even if its accessible from the original index page

**Comment by hexated** [comment]
> Shinobi seems to have added a new direct download link detected screen where it requires you to hit the download button in order to start the stream, maybe some special refferer or header is required as vlc is unable to play the raw link
> 
> As for Dahmer, for some reason sora cuts off part of the link, making the link invalid, even if its accessible from the original index page

Added referer into Shinobi and yeah, it only work with internal player now. Also dahmer works for me

**Comment by subby2006** [comment]
The problem with Dahmer is only with a few, mostly higher file size/remux sources. I'll show it to you on discord as I'll have to share links to the videos in order to show what's going wrong
