### ISSUE TITLE
[site request] www3.zoechip.com/

### ISSUE THREAD

**Issue by JoeTinnySpace** [hexated/cloudstream-extensions-hexated#112]
Link : https://www3.zoechip.com/

I would help with this if someone help me get started. I'm new in this neighborhood 🤠

The website is amazing. reliable and fast sources. 
![Uploading Screenshot_2023-02-25-12-57-08-556_org.mozilla.firefox.jpg…]()

**Comment by hexated** [comment]
> Link : https://www3.zoechip.com/
> 
> I would help with this if someone help me get started. I'm new in this neighborhood 🤠
> 
> The website is amazing. reliable and fast sources. 
> ![Uploading Screenshot_2023-02-25-12-57-08-556_org.mozilla.firefox.jpg…]()
> 

Sflix clone, install sflix in English repo. Its same
