### ISSUE TITLE
Suggestion for uhdmovies

### ISSUE THREAD

**Issue by venkat2305** [hexated/cloudstream-extensions-hexated#115]
It's better to have a separate extension for Uhd movies. Search for hobbit in sorastream. It's not available, since all of the three movies of the hobbit series are under one show. Aniyomi has a separate extension for Uhd movies and it looks like this.
![Screenshot_2023-02-28-17-19-00-774_xyz.jmir.tachiyomi.mi.debug.jpg](https://user-images.githubusercontent.com/55329452/221845825-6c442fd7-3ac6-4ca4-8a39-d66e72b58f86.jpg)

There are multiple cases like this. So, im  requesting for a separate extension for Uhd movies.
Thanks

**Comment by hexated** [comment]
> It's better to have a separate extension for Uhd movies. Search for hobbit in sorastream. It's not available, since all of the three movies of the hobbit series are under one show. Aniyomi has a separate extension for Uhd movies and it looks like this.
> ![Screenshot_2023-02-28-17-19-00-774_xyz.jmir.tachiyomi.mi.debug.jpg](https://user-images.githubusercontent.com/55329452/221845825-6c442fd7-3ac6-4ca4-8a39-d66e72b58f86.jpg)
> 
> There are multiple cases like this. So, im  requesting for a separate extension for Uhd movies.
> Thanks 

Pass..

Ask likdev maybe since he already make fdmovies too

**Comment by venkat2305** [comment]
Would you consider it when you have enough time , maybe? I'll ask him as well
