### ISSUE TITLE
Loklok repo still error, not fix in cloudstream. It is true are now are hard to get API key Loklok? But, i found other site use source Loklok still can watching.

### ISSUE THREAD

**Issue by abeqim** [hexated/cloudstream-extensions-hexated#116]
This site (Sora Anime Vercel App) are use Loklok source still can watching :- 
https://sora-anime.vercel.app/movies/505642/watch?provider=Loklok&id=29145

im just to know. how this sora developer still can get the API? how they do that?

**Comment by hexated** [comment]
> This site (Sora Anime Vercel App) are use Loklok source still can watching :- 
> https://sora-anime.vercel.app/movies/505642/watch?provider=Loklok&id=29145
> 
> im just to know. how this sora developer still can get the API? how they do that? 

Loklok work

**Comment by hexated** [comment]
> This site (Sora Anime Vercel App) are use Loklok source still can watching :- 
> https://sora-anime.vercel.app/movies/505642/watch?provider=Loklok&id=29145
> 
> im just to know. how this sora developer still can get the API? how they do that? 

Loklok works
