### ISSUE TITLE
Not being able to add

### ISSUE THREAD

**Issue by OshekharO** [hexated/cloudstream-extensions-hexated#129]
Hii I am not being able to add this repo. How can i install?

**Comment by hexated** [comment]
Join discord

**Comment by deolllllll** [comment]
link?

**Comment by OshekharO** [comment]
> Join discord

Joined but I am not able to find the link to install

**Comment by hexated** [comment]
Sorry but i can't link it in here, you should join discord and ask there..

**Comment by OshekharO** [comment]
> Sorry but i can't link it in here, you should join discord and ask there..

No problem I found the link

**Comment by zerakori** [comment]
Where is the link for discord
