### ISSUE TITLE
Hindi Anime and Cartoons

### ISSUE THREAD

**Issue by MRS73694** [hexated/cloudstream-extensions-hexated#14]
Hi, I am requesting a website for Hindi anime and cartoons.

https://anime-world.in/

Kindly add this in the repository, so that Indian viewers can get benefited.

**Comment by hexated** [comment]
Already added.
Check darkdemon repo

![Screenshot_20221004-051346.png](https://user-images.githubusercontent.com/37908684/193695507-d055ccd6-0d7e-4fa2-81d4-18bbe60df30d.png)
