### ISSUE TITLE
sorry for bothering you but can you make an Arabic extension please

### ISSUE THREAD

**Issue by Piratealgeria** [hexated/cloudstream-extensions-hexated#143]
here are few sites that have great content

(best) : https://witanime.com/ 
(2nd best) https://c.gateanime.com/ 
(good ) : https://w1.anime4up.tv/
https://www.faselhd.one/
https://www.animeiat.tv/
https://www.zimabadk.com/

the other Arabic extension have some issues

**Comment by hexated** [comment]
I'm sorry but I don't do arab,.u should ask in arab repo

**Comment by Piratealgeria** [comment]
sorry for bothering you can you delete this issue please
