### ISSUE TITLE
Time Out and Failed to connect

### ISSUE THREAD

**Issue by Ashlyn07** [hexated/cloudstream-extensions-hexated#145]
Animeindo, Animesail, Drama serial, Kuramanime, Kuronime, Layarkaca, Multiplex, Neonime, NontonAnimeID, Oploverz, Otakudesu, Rebahin, Samehadaku, Useetv.

I have try any method like change DNS, change my ISP, use VPN, but the results is same, always timeout.
Can you check Is this problem from extension or my device?

P.S : sorry for my elite English, i hope u understand

**Comment by hexated** [comment]
Saya orang Indo 😅

Kalau Masih nggk bisa clear cache Dan restart apk

**Comment by Ashlyn07** [comment]
Dah bisa mas, tapi kuronime lagi yg bermasalah mas, semua episode nya "no link founds" semua

Maaf kalo ngerepotin mas

**Comment by shamcheani** [comment]
Ooo. Mas hexated org Indonesia ya. Kita serumpun mas
