### ISSUE TITLE
Bug Paradisehill with vlc

### ISSUE THREAD

**Issue by owencz1998** [hexated/cloudstream-extensions-hexated#15]
I want to use vlc as my main media player but paradisehill doesn't like to load with it not sure if this can be fixed dude.

![Screenshot_20221006_180503_CloudStream Beta.jpg](https://user-images.githubusercontent.com/96526481/194376469-1d68e7d5-6b67-4578-b545-10d58fbdfebb.jpg)

**Comment by hexated** [comment]
All video?
I can't replicates that, cause its working for me
![Screenshot_20221007-043636.png](https://user-images.githubusercontent.com/37908684/194423299-569687ed-439d-44b4-ad35-491598843699.png)

What series that not working for you?

**Comment by owencz1998** [comment]
It only doesn't work for paradisehill nsfw

**Comment by hexated** [comment]
ahh idk only paradisehill.. lol

fixed

**Comment by owencz1998** [comment]
Thanks dude haha
