### ISSUE TITLE
[Feature Request]Anime database

### ISSUE THREAD

**Issue by ghost** [hexated/cloudstream-extensions-hexated#152]
In sorastream separate anime section using database of kitsu, anilist or myanimelist adding would be appreciated.
This issue is by tmbd database correct anime is not provided through parsers.

**Comment by hexated** [comment]
I think it's better to make it as a sepererate provider. But I don't have time doing it anytime soon

Also I've made my own mapping to convert tmdb into animeid. I know it's not perfect but I think it way better then before
