### ISSUE TITLE
Loklok bug

### ISSUE THREAD

**Issue by Amadeuss77** [hexated/cloudstream-extensions-hexated#155]
Hello, unfortunately i cant watch loklok after 2 episode, eps 1-2 is fine but when play eps 3, its showing some error, can you solve this hexa ? Thanks for the hardwork!
![Screenshot_2023-06-01-10-29-15-51_a153ad7195ab131f51b38ebe0eab4033](https://github.com/hexated/cloudstream-extensions-hexated/assets/135193208/57e628c0-110e-42d0-9bb2-c147c03cfef6)

**Comment by retiarylime** [comment]
I am also experiencing the same error.
