### ISSUE TITLE
Kuronime no links found

### ISSUE THREAD

**Issue by Ashlyn07** [hexated/cloudstream-extensions-hexated#156]
Banyak source stream yg hilang di websitenya bang jadinya rata2 episode baru no links found 
![Screenshot_2023-06-02-09-54-11-19_a153ad7195ab131f51b38ebe0eab4033](https://github.com/hexated/cloudstream-extensions-hexated/assets/85921518/0b4c92b5-616b-4597-8afa-3dc717881aae)

**Comment by hexated** [comment]
Works fine disini, coba update apk ke latest pre

**Comment by Ashlyn07** [comment]
Oh iya bener bang, harus pakai yg versi Beta ternyata, ty ty
