### ISSUE TITLE
Krakenfiles error

### ISSUE THREAD

**Issue by Ashlyn07** [hexated/cloudstream-extensions-hexated#159]
Semua source yang make krakenfiles gak bisa bang, dah ku coba di kuronime sama animesail, pas media player nya kuubah ke web browser jadinya 403 forbidden, kalo dari websitenya langsung masih bisa play.

P.s : cloudstream nya udah make versi Beta yang paling baru

![Screenshot_2023-06-12-12-00-46-73_cfa2fd239c8cded9285432912d0e0818](https://github.com/hexated/cloudstream-extensions-hexated/assets/85921518/66421467-f3a1-4171-b339-0e26b17d7366)

![Screenshot_2023-06-12-12-00-49-69_cfa2fd239c8cded9285432912d0e0818](https://github.com/hexated/cloudstream-extensions-hexated/assets/85921518/265e1d87-4bf9-4c9a-96c0-2489dab710e0)

![Screenshot_2023-06-12-12-15-54-83_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/hexated/cloudstream-extensions-hexated/assets/85921518/05594a78-5906-41ff-a0a0-627cba7372c4)

![Screenshot_2023-06-12-12-06-45-32_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/hexated/cloudstream-extensions-hexated/assets/85921518/a8e9ee76-5866-4a45-a278-0e453c6c4e92)

**Comment by Onedore7** [comment]
Mcm mna masukkan link kedalam cloudstream ya?

**Comment by hexated** [comment]
> Mcm mna masukkan link kedalam cloudstream ya?

Join discord channel and ask there
