### ISSUE TITLE
[ Site Request ] please consider this one

### ISSUE THREAD

**Issue by OshekharO** [hexated/cloudstream-extensions-hexated#16]
This site uses IMDb I'd for playing movie like 2embed but this source shows movies in Hindi unlike 2embed which plays in English.

https://free4uplay.xyz/play/{IMDb}

Movie Example: https://free4uplay.xyz/play/tt1745960

Series Example: https://free4uplay.xyz/play/tt10857160

**Comment by OshekharO** [comment]
@hexated any news on this?

**Comment by hexated** [comment]
Can't play video
