### ISSUE TITLE
Animesail dan kuronime

### ISSUE THREAD

**Issue by Ashlyn07** [hexated/cloudstream-extensions-hexated#167]
Habis update app cloudstreamnya tadi kuronime sama animesail jadi no link semua bang, mau downgrade tapi gabisa 😭 yg versi stable juga sama no link semua 😭

https://github.com/hexated/cloudstream-extensions-hexated/assets/85921518/273f42cc-e499-425a-9618-fb797487587c

**Comment by Ashlyn07** [comment]
Bang punya apk Beta nya yg belum diupdaye ga?

**Comment by hexated** [comment]
> Bang punya apk Beta nya yg belum di-update ga?

Check disini https://github.com/recloudstream/cloudstream-archive

**Comment by Ashlyn07** [comment]
Gaada yg bisa bang dah kucoba semua, krakenfiles nya gak ke detect

**Comment by hexated** [comment]
close as duplicate with #168
