### ISSUE TITLE
[Site Request] Enime

### ISSUE THREAD

**Issue by bachig26** [hexated/cloudstream-extensions-hexated#17]
Domain: https://enime.moe

GitHub Repo (Official) for Enime API and Docs for building: https://github.com/Enime-Project

EnimeSource.kt from different project: https://github.com/fakeyatogod/AnimeScrap/blob/main/app/src/main/java/com/talent/animescrap/animesources/EnimeSource.kt

**Comment by hexated** [comment]
Sorry just checked, enime just gogo and zoro
