### ISSUE TITLE
Anichi Mal Sync bug

### ISSUE THREAD

**Issue by KillerDogeEmpire** [hexated/cloudstream-extensions-hexated#172]
Sometimes it shows that an anime has mal and anilist sync, and then sometimes it's just gone...

Please hexated my lord, I beg of you please fix it. I can't live without my anime being synced while watching 
![Screenshot_20230707_220248_CloudStream Beta](https://github.com/hexated/cloudstream-extensions-hexated/assets/87155550/64da0f23-eff8-46bd-918c-cdd903fc98c6)
![Screenshot_20230707_215936_CloudStream Beta](https://github.com/hexated/cloudstream-extensions-hexated/assets/87155550/349b78fa-5789-4a56-a2f4-9422c9140353)

**Comment by KillerDogeEmpire** [comment]
It happens on all anime, where it occasionally has sync, then no longer has sync.

**Comment by KillerDogeEmpire** [comment]
It happens randomly though. However once the sync is missing, it's hard to get it to show back.

**Comment by hexated** [comment]
> Sometimes it shows that an anime has mal and anilist sync, and then sometimes it's just gone...
> 
> Please hexated my lord, I beg of you please fix it. I can't live without my anime being synced while watching 
> ![Screenshot_20230707_220248_CloudStream Beta](https://github.com/hexated/cloudstream-extensions-hexated/assets/87155550/64da0f23-eff8-46bd-918c-cdd903fc98c6)
> ![Screenshot_20230707_215936_CloudStream Beta](https://github.com/hexated/cloudstream-extensions-hexated/assets/87155550/349b78fa-5789-4a56-a2f4-9422c9140353)
> 

Test again

**Comment by KillerDogeEmpire** [comment]
Thanks hexated, it works.
