### ISSUE TITLE
Request from me Donghua site  [ Kazefuri ]

### ISSUE THREAD

**Issue by IfanID** [hexated/cloudstream-extensions-hexated#181]
I recommend the Donghua site with Indonesian subtitles, because there is no plugin that contains Donghua, mostly Japanese anime. 

I ask you to please add : [Kazefuri](https://kazefuri.net/) 

Thank You

**Comment by hexated** [comment]
> I recommend the Donghua site with Indonesian subtitles, because there is no plugin that contains Donghua, mostly Japanese anime. 
> 
> I ask you to please add : [Kazefuri](https://kazefuri.net/) 
> 
> Thank You 

Dude fix your sentence..
Kalo nggk bisa bhs inggris pake bhs indo aj..

**Comment by IfanID** [comment]
Baru tau kamu orang indo ya formal aja la make bahasa inggris walaupun masih kacau, contoh ngomong sama orang luar masa make bahasa Indonesia gimana mau di tangepin terus ya nga sopan la namanya juga media online
