### ISSUE TITLE
Error pada DramaSerial

### ISSUE THREAD

**Issue by IfanID** [hexated/cloudstream-extensions-hexated#183]
Error Parent job is cancelling &
![Screenshot_2023-07-14-09-36-28-35_a153ad7195ab131f51b38ebe0eab4033](https://github.com/hexated/cloudstream-extensions-hexated/assets/69411810/49b6ceec-4000-4bd7-850c-8624d4b8a8e8)

**Comment by hexated** [comment]
> Error Parent job is cancelling &
> ![Screenshot_2023-07-14-09-36-28-35_a153ad7195ab131f51b38ebe0eab4033](https://github.com/hexated/cloudstream-extensions-hexated/assets/69411810/49b6ceec-4000-4bd7-850c-8624d4b8a8e8)
> 

Works fine for me, try changing dns or use VPN

![Uploading Screenshot_20230715-220232.png …]()
