### ISSUE TITLE
Anichi sync bug

### ISSUE THREAD

**Issue by KillerDogeEmpire** [hexated/cloudstream-extensions-hexated#185]
I know it had an update that recently fixed most of the sync problems, but it seems that some animes wit alt names like black clover being named B.C makes it not have sync

**Comment by KillerDogeEmpire** [comment]
![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/87155550/638927d6-24cb-4940-b0e6-ec98c10cdc7c)
 
 here is proof I am signed into my anilist and mal account
 
![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/87155550/0833c677-4044-4c0a-a007-6e33af6ede43)

**Comment by KillerDogeEmpire** [comment]
also some anime in the movies section don't have sync
![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/87155550/51891e7d-7a47-40d7-a8a7-4251831f2723)

**Comment by hexated** [comment]
> also some anime in the movies section don't have sync
> ![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/87155550/51891e7d-7a47-40d7-a8a7-4251831f2723)
> 
> 

I Made my own mapping on this. Like getTracker that you've made using consumet. And u know it impossible to get all content since they don't directly provide malid

**Comment by KillerDogeEmpire** [comment]
I know. Sorry for this issue again, I will close it
