### ISSUE TITLE
Update idlix

### ISSUE THREAD

**Issue by qolbudr** [hexated/cloudstream-extensions-hexated#188]
idlix gabisa filmnya gamuncul

**Comment by hexated** [comment]
Works fine disini...
![Screenshot_20230716-123453.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/f21e5000-d39f-40c6-8857-4a4e84364187)

Elaborate

**Comment by qolbudr** [comment]
![Screenshot_2023-07-16-12-38-41-64_cfa2fd239c8cded9285432912d0e0818.jpg](https://github.com/hexated/cloudstream-extensions-hexated/assets/61232165/02acd8a3-e4e3-4946-b4b2-a0e9f94af444)

gabisa :(

**Comment by b4byhuey** [comment]
Idlix ganti domain jadi https://tv.idlixprime.com dan pasang Cloudflare di webnya

**Comment by prdxinfinity** [comment]
@b4byhuey is it mean that we cant acces it anymore ?
