### ISSUE TITLE
Site request donghua

### ISSUE THREAD

**Issue by afifn** [hexated/cloudstream-extensions-hexated#189]
mas, request site anichin dan animexin, makasih

**Comment by hexated** [comment]
> mas, request site anichin dan animexin, makasih

Link

**Comment by afifn** [comment]
> > mas, request site anichin dan animexin, makasih
> 
> Link

https://anichin.top/ dan https://animexin.vip/

**Comment by afifn** [comment]
tambah https://auratail.com/ kalau bisa, makasih
