### ISSUE TITLE
extractor for watchomovies

### ISSUE THREAD

**Issue by Thorodinson1** [hexated/cloudstream-extensions-hexated#194]
i tried to make the extractor from watchomovies  which is similar like speedostream but it cant is not working can tell what is wrong with the code 

package com.lagradost.cloudstream3.extractors

import com.fasterxml.jackson.annotation.JsonProperty
import com.lagradost.cloudstream3.app
import com.lagradost.cloudstream3.utils.AppUtils.tryParseJson
import com.lagradost.cloudstream3.utils.ExtractorApi
import com.lagradost.cloudstream3.utils.ExtractorLink
import com.lagradost.cloudstream3.utils.getAndUnpack
import com.lagradost.cloudstream3.utils.Qualities
import com.lagradost.cloudstream3.utils.M3u8Helper
import org.jsoup.select.Elements

class StreamoUpload1 : StreamoUpload() {
    override val mainUrl = "https://streamoupload.xyz"
}

open class StreamoUpload : ExtractorApi() {
    override val name = "StreamoUpload"
    override val mainUrl = "https://streamoupload.xyz"
    override val requiresReferer = true

    override suspend fun getUrl(url: String, referer: String?): List<ExtractorLink> {
        val sources = mutableListOf<ExtractorLink>()
        val response = app.get(url, referer = referer)
        val scriptElements = response.document.select("script").map { script ->
              if (script.data().contains("eval(function(p,a,c,k,e,d)")) {
                val data = getAndUnpack(script.data()).substringAfter("sources: [").substringBefore("],").replace("file", "\"file\"").trim()                                      
                tryParseJson<File>(data)?.let {
                        M3u8Helper.generateM3u8(
                            name,
                            it.file,
                            "$mainUrl/",
                        ).forEach { m3uData -> sources.add(m3uData) }
                    }
                }
            }
            return sources
        }
    
        private data class File(
            @JsonProperty("file") val file: String,
        )
    
    
    }

**Comment by hexated** [comment]
Send me link of website, so i can check

**Comment by Thorodinson1** [comment]
It's  also has NSFW content  https://watchomovies.mom/

**Comment by hexated** [comment]
space issue

instead
```
.substringAfter("sources: [")
```

try
```
.substringAfter("sources:[")
```

**Comment by Thorodinson1** [comment]
Ok

**Comment by Thorodinson1** [comment]
ok bro the extractor is working
