### ISSUE TITLE
Please add some provider 

### ISSUE THREAD

**Issue by prdxinfinity** [hexated/cloudstream-extensions-hexated#195]
Hi @hexated ,
Please try to add provider to your repo with the following list below :
No	Provider		        Address						IP							Status
1	Animesave		https://animesave.web.id/	        NA							new
2	CGVindo			NA							http://198.54.124.245/		new
3	Cinemaindo		NA							http://103.15.226.148/		new
4	IdlixProvider	        https://tv.idlixprime.com/	        NA						update
5	IndoXXI			https://indoxxi.stream		        http://103.15.226.138/		new
6	Layarindo		NA							https://77.91.103.81/		new
7	Multiplex21		NA							http://5.104.81.46/			update
8	Rebahin			NA							http://212.52.1.251/		update

very appreciate to you because we can enjoy a cup of coffee in our beloved home watching movie.
thank you :)

**Comment by joepermana94** [comment]
@hexated let me add some sites..
1. Dutamovie provider https://dutamovie21.live/
2. Javsubok https://javsubok.com/

**Comment by prdxinfinity** [comment]
There are 2 different IP for Rebahin http://212.52.1.251/ (for Rebahin21) and http://179.43.163.50/ (for Rebahin). They were both refers to Rebahin. if possible, please add to the repo all of them :) @hexated
