### ISSUE TITLE
Rebahin Bug

### ISSUE THREAD

**Issue by renatobasa88** [hexated/cloudstream-extensions-hexated#198]
The Rebahin site is inaccessible. this is the new Rebahin link http://198.54.124.245/

**Comment by prdxinfinity** [comment]
I try to open it, but it shows seems like CGVindo not rebahin.
![Screenshot_2023-07-20-12-28-37-669_com android chrome](https://github.com/hexated/cloudstream-extensions-hexated/assets/139616094/2c4e5b69-031b-43ff-a613-99c9b969274f)

**Comment by renatobasa88** [comment]
Yeah new Rebahin 1.6 refers to CGVIndo.

**Comment by b4byhuey** [comment]
No Rebahin is http://179.43.163.50/ now
