### ISSUE TITLE
Gdrive player error 

### ISSUE THREAD

**Issue by joepermana94** [hexated/cloudstream-extensions-hexated#199]
Halo @hexated I found a problem playing a video through the GDRIVE player. the video can be played but not long after that there is an error message "ERROR_CODE_IO_READ_POSITION_OUT_OF RANGE (2008) SOURCE ERROR". after that the video stops immediately, you have to click again to play and it happens continuously. can you fix it?
![Screenshot_20230721-004937](https://github.com/hexated/cloudstream-extensions-hexated/assets/139651590/3c3e51af-e419-437c-862f-8fc2925a89e2)

**Comment by hexated** [comment]
This is exo issue, open this in cloudstream repo
