### ISSUE TITLE
Paradisehill 

### ISSUE THREAD

**Issue by owencz1998** [hexated/cloudstream-extensions-hexated#2]
Hi Iv been told you the guy to come to but obviously u can ignore me but I would really like this website to be added for nsfw movies I tried to code it myself and failed 😂sorry if u didn't want requests on your repo.

https://en.paradisehill.cc/porn/

**Comment by hexated** [comment]
fixed

**Comment by owencz1998** [comment]
U are a legend thanks so much man 😄😄
