### ISSUE TITLE
Error SoraStream No links found Session ID must be unique. ID=

### ISSUE THREAD

**Issue by pmg1991** [hexated/cloudstream-extensions-hexated#208]
SoraStream v152
App version pre-release https://github.com/recloudstream/cloudstream/commit/7c60ccdef274ef5cc377d3d376d4909642cf6d9b

**Comment by hexated** [comment]
> 
> SoraStream v152
> App version pre-release https://github.com/recloudstream/cloudstream/commit/7c60ccdef274ef5cc377d3d376d4909642cf6d9b

Try reinstall sora and clear cache

**Comment by subby2006** [comment]
> > SoraStream v152
> > App version pre-release [recloudstream/cloudstream@7c60ccd](https://github.com/recloudstream/cloudstream/commit/7c60ccdef274ef5cc377d3d376d4909642cf6d9b)
> 
> Try reinstall sora and clear cache

Have tried that but didn't work. Do I need to downgrade the app or should I wait for fixes?

**Comment by hexated** [comment]
> > > SoraStream v152
> > > App version pre-release [recloudstream/cloudstream@7c60ccd](https://github.com/recloudstream/cloudstream/commit/7c60ccdef274ef5cc377d3d376d4909642cf6d9b)
> > 
> > Try reinstall sora and clear cache
> 
> Have tried that but didn't work. Do I need to downgrade the app or should I wait for fixes?

Try fully reinstall app. But backup first

**Comment by jackuars7** [comment]
I faced the same issue with Sorastream and YuugenAnime with the latest update. Full reinstall only fixed the issue for a short period of time. When launching it after a few hours I get the same error.

When playing with an external player I don't face this issue though. So it should be somthing related to the internal player.

**Comment by pmg1991** [comment]
with latest, selected subtitles are not loading

**Comment by jackuars7** [comment]
Same for me no subtitles

**Comment by self-similarity** [comment]
Subtitle issues was caused by an upstream bug, not this repository.

**Comment by self-similarity** [comment]
Session ID was also upstream and fixed here: https://github.com/recloudstream/cloudstream/pull/534
