### ISSUE TITLE
ANIME WORLD

### ISSUE THREAD

**Issue by Thorodinson1** [hexated/cloudstream-extensions-hexated#217]
Can you add    https://anime-world.in/   it was in darkdemon repo now the repo is not maintained  ( https://github.com/daarkdemon/cs-darkdemon-extensions )   and it is no longer working . 

it is also in aniyomi repositry   (  https://github.com/aniyomiorg/aniyomi-extensions/tree/master/src/all/animeworldindia/src/eu/kanade/tachiyomi/animeextension/all/animeworldindia   ) 

may be few modification will do as they have updated the site couple of months back

**Comment by HaxerAhmed** [comment]
@hexated sir there is huge demand of hindi cartoon and animation plz add a hindi repo like sora stream 🥺

**Comment by hexated** [comment]
It's in likdev repo now, maybe ask him to fix (if it doesn't work)
