### ISSUE TITLE
Site request! Germany. bs.to, cine.to and s.to Pls add these sites.

### ISSUE THREAD

**Issue by kekbrott** [hexated/cloudstream-extensions-hexated#218]
Hello, 

It would be very nice if the sites **bs.to, s.to and cine.to** would be add to this repo.
The german sites, expect aniworld, aren‘t working properly and this sites listed above are popular in Germany.
So please add these sites. It would be nice for german watchers.

**Comment by hexated** [comment]
- Aniworld works fine
- s.to already included in Aniworld
- others two have captcha
