### ISSUE TITLE
Register Tmdb ID in LoadResponse

### ISSUE THREAD

**Issue by self-similarity** [hexated/cloudstream-extensions-hexated#224]
Please register the ids you have when creating LoadResponses using the following:

https://github.com/recloudstream/cloudstream/blob/bbbb7c4982d6f83f236883e2a9ed40d7a2b8eb61/app/src/main/java/com/lagradost/cloudstream3/MainAPI.kt#L1265-L1279

The functions are currently placeholders but they will be instrumental to the simkl implementation I am working on currently :gorilla:

**Comment by hexated** [comment]
nice 👍 
add supports syncIds for getLoadUrl too, so we can autosync from different device
https://github.com/recloudstream/cloudstream/blob/2d65aefc760575dce121960906725b9ad04c39be/app/src/main/java/com/lagradost/cloudstream3/metaproviders/SyncRedirector.kt#L10
