### ISSUE TITLE
Oploverz Problem speed control

### ISSUE THREAD

**Issue by zednite** [hexated/cloudstream-extensions-hexated#238]
Mohon coba dicek, tidak bisa di per cepat atau back forward di setiap film² terbarunya

**Comment by hexated** [comment]
Coba ganti source atau pake external player. Issue nya dari internal player can't decode video

**Comment by zednite** [comment]
om, gw mau sekali2 donasi ada rezeki lebih nti gw donasi lagi
kasi link donasi klo ada
