### ISSUE TITLE
some player extractors disappeared and layarkaca can't generate search.

### ISSUE THREAD

**Issue by joepermana94** [hexated/cloudstream-extensions-hexated#254]
1. Layarkaca provider cannot produce searches, while the film I am looking for is on layarkaca 
![Screenshot_20230901-140829](https://github.com/hexated/cloudstream-extensions-hexated/assets/139651590/96e76814-7b4c-4e34-b3cc-096e4d5d4331)
![Screenshot_20230901-140909](https://github.com/hexated/cloudstream-extensions-hexated/assets/139651590/977a707a-2b45-4f50-9504-96d1a3ee5b06)

2 Ngefilm provider can't read BEASTX, MIRROR and ABYSS video extractors so some movies can't be played

3. Nodrakor id provider unable to play new episodes 

4. Dutamovie can't read BEASTX video Extractor.

5. Idlix provider error again (no link found)

I am very grateful because you can share for free, but if you want to accept donations from us. We also won't hesitate to give. because there are people using your repo to make money. but you can't do anything. Thank you

**Comment by hexated** [comment]
I can't scrape abyss & mirror. But others should works fine now

Idlix may f up soon. Cause they actively change their code & I might give up fixing it

**Comment by joepermana94** [comment]
@hexated  it's okay, you've tried your best. at this time it's better not to update idlix first. Thank you for providing movies for free.
