### ISSUE TITLE
Aniwatch: mark links as sub/dub

### ISSUE THREAD

**Issue by JimZiii** [hexated/cloudstream-extensions-hexated#282]
None of the links on aniwatch are marked sub or dub so you have 4 megacloud links of each resolution  with the exact same name (two for each language) and you're forced to randomly try them till you find the one you want to watch, on every single episode.
The links are never in the same order so some episodes the first one is dub, sometimes the second, and other times the 3rd. You're also only able to prioritize for resolution in cloudstream since they all got the same name.

Adding sub or dub to their names would make it possible for cloudstream to prioritize for sub/dub and handle it automatically instead.

The dub/sub links are in separate categories on the aniwatch website so you should be able to differentiate between them somehow. I've seen other providers that have links marked sub/dub, so it's possible

**Comment by hexated** [comment]
I didn't make aniwatch
