### ISSUE TITLE
Support m4uhd

### ISSUE THREAD

**Issue by Luna712** [hexated/cloudstream-extensions-hexated#283]
It would be nice if ww1.m4uhd.tv and ww2.m4ufree.com could be properly supported in SoraStream. Currently if you play a movie that does exist on both those, it still returns "No links found" when trying to play them with SoraStream.

**Comment by hexated** [comment]
Playm4u & M4ufree are M4uhd

**Comment by Luna712** [comment]
It works for some things now, trying random movies 2 worked, a couple didn't such as https://ww2.m4ufree.com/watch-teeo-dark-rising-bring-your-battle-axe-2007-movie-online-free-m4ufree.html, which returns "No Links Found" still when trying to play on CloudStream.

**Comment by Luna712** [comment]
It still doesn't work for the one I mentioned above.
