### ISSUE TITLE
Some Netflixmirror links not appearing on sora

### ISSUE THREAD

**Issue by Rayforest** [hexated/cloudstream-extensions-hexated#285]
These are some of the movies that I tested which worked fine on https://m.netflixmirror.com/ but they are not showing links on sora for some reason (I tried with proton vpn too for added measure):

1. Ahaan (2021)
2. Friday Night Plan (2023)
3. Ariyippu (2022)
4. Padmini (2023)
5. Vikruthi (2019)

Also thanks a lot for adding this site to sora. A much needed addition to the already excellent provider like sora. It would be even more better if they add other OTT platforms too as they say on their site. Much love 🥰❤️

**Comment by Rayforest** [comment]
Thank you. I checked them and it seems two of them are still not loading links. Ariyippu and Vikruthi

**Comment by hexated** [comment]
Yeah, can't fix. Issue with cross revering
