### ISSUE TITLE
BEASTX player extractor disappeared

### ISSUE THREAD

**Issue by joepermana94** [hexated/cloudstream-extensions-hexated#289]
hello @hexated, the BEASTX video player seems to be missing so Dutamovie and ngefilm can't be played
Thank you

**Comment by b4byhuey** [comment]
Ngefilm masih error, masih Link not found.

**Comment by hexated** [comment]
> Ngefilm masih error, masih Link not found.

Reinstall provider + clear cache

**Comment by b4byhuey** [comment]
> > Ngefilm masih error, masih Link not found.
> 
> Reinstall provider + clear cache

Habis update tadi udah bisa om, tpi barusan ane coba lagi error lagi..

**Comment by joepermana94** [comment]
Halo @hexated, It looks like the BEASX extractor has an error on ngefilm, the domain changed is still the same. In fact, the Korean series disappeared after changing domains. It's best if the domain remains https://nge-film21.site/. Only the beasx has been repaired on ngefilm. Duta movie solved
Thank You
