### ISSUE TITLE
Filmxy links are gone. 

### ISSUE THREAD

**Issue by Jeenesh7** [hexated/cloudstream-extensions-hexated#291]
Checked on various movies and series, reload links as well but still not appearing.

**Comment by hexated** [comment]
Works fine for me
![Screenshot_20230922-053008.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/8dc52224-0f44-41c1-9d37-0a4329d6fba5)

Use pre, change DNS or try VPN
