### ISSUE TITLE
Please move Dahmer position 

### ISSUE THREAD

**Issue by warchild679** [hexated/cloudstream-extensions-hexated#293]
This is specifically for tv shows for example Witcher season 3 episode 1 one Dahmer link shows up it usually takes like a minute or so for the rest of links to pop up but with the Dahmer links its a hit or miss I get this source error an it kicks me out which is annoying so it should be moved not removed just not on top you could put Dbgo,Vidsrc or Smashy links thats guaranteed to work so that the rest of links can pop up.

**Comment by hexated** [comment]
Learn how to use sources profile
