### ISSUE TITLE
some player extractors are missing

### ISSUE THREAD

**Issue by joepermana94** [hexated/cloudstream-extensions-hexated#295]
Halo @hexated. beasx, filelions, chilx, streamwish,  and vcloud extractor are missing so on some providers such as Ngefilm and Dutamovie can't be played, Krakenfiles buffering problem.
Thank you

**Comment by LuduPro** [comment]
Same with moviehab (tagalog) hope you could fix it for filipino viewers 🙏

**Comment by joepermana94** [comment]
Hai @hexated  all types of dutamovie films are the same
![Screenshot_20230926-151741_1](https://github.com/hexated/cloudstream-extensions-hexated/assets/139651590/43e54365-b2dc-4624-a6dc-b0c6c5956465)
