### ISSUE TITLE
Hdfilmcehennemi bugs and subtitle not working

### ISSUE THREAD

**Issue by Tolga077** [hexated/cloudstream-extensions-hexated#3]
Series category does not work. I think this is the correct link it will work if you add this. also rapidrame subtitles are not working. 
![IMG_20220918_201848](https://user-images.githubusercontent.com/105724628/190920641-afcec55a-ba17-4847-95ed-b7c8bc89aaac.png)
Correct link :
" https://www.hdfilmcehennemi.live/yabancidiziizle/page/ "

When I click on this, the subtitles work on the website. 
![IMG_20220918_202528](https://user-images.githubusercontent.com/105724628/190920663-d6182274-6c5a-4cc9-a27d-64b966b3643e.png)

**Comment by hexated** [comment]
fixed

**Comment by Tolga077** [comment]
They changed the links. 
Old one
$mainUrl/yabancidiziizle/page
New one
https://www.hdfilmcehennemi.live/yabancidiziizle-1/page

Old one
$mainUrl/category/tavsiye-filmler-izle1/page

New one 
https://www.hdfilmcehennemi.live/category/tavsiye-filmler-izle2/page

**Comment by Tolga077** [comment]
> fixed

The site address has changed. https://www.hdfilmcehennemi.life/

Old one
$mainUrl/yabancidiziizle/page
New one
https://www.hdfilmcehennemi.life/yabancidiziizle-1/page

Old one
$mainUrl/category/tavsiye-filmler-izle1/page

New one
https://www.hdfilmcehennemi.life/category/tavsiye-filmler-izle2/page
