### ISSUE TITLE
Please replace animixplay with this one

### ISSUE THREAD

**Issue by KillerDogeEmpire** [hexated/cloudstream-extensions-hexated#308]
https://animixplay.tube

It is a clone of animixplay from when it shut down, however it has a lot of sources including filelions, dood, mp4, gogo, vidstream, the animixplay sources, and more. It would be a great edition. and please if you do add this, make the sub and dub categories like you have done to anichi. Hoping this will get added since will be more reliable then aniwave, and will have sync on every anime unlike anichi

**Comment by KillerDogeEmpire** [comment]
Also gogo no longer works so this would be great

**Comment by hexated** [comment]
Gogo still works for me. And this is just gogo scraper
