### ISSUE TITLE
Use AnimixPlay as a source too, apart from only GoGo

### ISSUE THREAD

**Issue by Xorio71** [hexated/cloudstream-extensions-hexated#31]
Would it be possible to add AnimixPlay as a source too, instead of only GoGo? As it currently is, the extension only provides links from GoGo, which are honestly pretty hit-or-miss in some aspects (Like subs and sound quality).

If you don't want to do it, it's fine, but I would really appreciate if you did. Thanks!

**Comment by rollingmoai** [comment]
Animixplay is dead now

**Comment by Xorio71** [comment]
Yup, I know.

**Comment by rollingmoai** [comment]
You can close this issue now, then 🙂

**Comment by Xorio71** [comment]
Will do.
