### ISSUE TITLE
Links not appearing for webseries in sora

### ISSUE THREAD

**Issue by aadio7** [hexated/cloudstream-extensions-hexated#311]
So gofile and vcloud which actually contains vegamovies content... so i can only get most of movies with these vega sources.. and but in some movies and all series i am not getting vcloud and gofile source ... please solve this in update
![Screenshot_20231009-174224_CloudStream Beta](https://github.com/hexated/cloudstream-extensions-hexated/assets/147267681/bbd00860-b4f7-47f4-8b3d-8d7cabe4e97b)
is in update
![Screenshot_20231009-174512_CloudStream Beta](https://github.com/hexated/cloudstream-extensions-hexated/assets/147267681/b02e78fa-d99b-425c-bccc-cd6e0b40b749)

**Comment by hexated** [comment]
Can you list all shows that didn't appear

**Comment by aadio7** [comment]
> Can you list all shows that didn't appear

I cant find in any webseries even the famous one doesnt have vega sources.... whereas in movies it is available for every movies....so you have to fix the webseries thing since movie doesnt have the problem

**Comment by aadio7** [comment]
Every webseries have this problems... as i send you the SS ... that every movie have vega sources but none of the webseries have vega sources..

**Comment by aadio7** [comment]
You have not added movies from section of "marvel cinematic universe " and "movies collection" which are in vega category

**Comment by aadio7** [comment]
> Can you list all shows that didn't appear

Every webseries have this problems... as i send you the SS ... that every movie have vega sources but none of the webseries have vega sources.. and other than that You have not added movies from section of "marvel cinematic universe " and "movies collection" which are in vega category

**Comment by aadio7** [comment]
Bruuhhh the issue is not fixed... still no gofile and vcloud links for any webseries

**Comment by aadio7** [comment]
Thanks brdr for solving it❤️🛐

**Comment by aadio7** [comment]
Idk but links are only available for latest ones like which released in 2023 series even old season doesnot have gofile and vcloud... just the latest ones...
