### ISSUE TITLE
Stremiox bug

### ISSUE THREAD

**Issue by oathzed** [hexated/cloudstream-extensions-hexated#313]
I have stremio x cloned with an addon, the addon works fine but when I open cloudstream like 50% of the time it won't open the added it was last on, it will just say "none" 

Video for showing what happens:

https://imgchest.com/p/o24azqg37lj

**Comment by hexated** [comment]
This is not issue with provider, open issue in main app

**Comment by oathzed** [comment]
> This is not issue with provider, open issue in main app

Ahh ok got it, thanks
