### ISSUE TITLE
Extension request

### ISSUE THREAD

**Issue by JimZiii** [hexated/cloudstream-extensions-hexated#315]
Can you please add aniwatch.to to your hexated repo?

I'd also like to ask for it to have library support like you've done with yugenanime and anichi

**Comment by hexated** [comment]
Already in English repo

**Comment by JimZiii** [comment]
Yes i know but that one doesnt have sub and dub mirrors separately, they're all named the same where you have to randomly try them till you find the one you want to watch, every single time it's a new episode.
It also doesn't have library support and both the codeberg for the original repo and the github for stormunblesseds seems completely abandoned when it comes to creating issues and trying to communicate any information about it.

But sure, i get it if you still think it's unnecessary
