### ISSUE TITLE
Links issue

### ISSUE THREAD

**Issue by Jeenesh7** [hexated/cloudstream-extensions-hexated#316]
Filmxy links have disappeared. I have checked the movies Gran Turismo, Moonfall, Overhaul and it's not there. I have also used Cloudflare dns, Google dns, is using pre-release, used VPN (windscribe), reinstalled the extension, cleared cache and nothing works. Please check the issue. Thank you.

**Comment by hexated** [comment]
Working fine here
![Screenshot_20231011-125719.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/1d5cb1db-d332-4a16-b382-abd7fa271916)
