### ISSUE TITLE
Hindi/Indian extension request 

### ISSUE THREAD

**Issue by aadio7** [hexated/cloudstream-extensions-hexated#321]
There is only 1 good extension  for hindi that is hdmovie2 in movierulzhd in hexated I think u should add
https://mkvcinemas.boo/ as another hindi extension it has hindi content in highest quality(it has every content labelled as webrip in poster whereas inside there are webdl,bluray and webrip formats link)

**Comment by SaurabhKaperwan** [comment]
Sorastream have many hindi content like uhdmovies, vegamovies,multimovies and many more

**Comment by aadio7** [comment]
> Sorastream have many hindi content streams like uhdmovies, vegamovies,multimovies,gofile,showflix and many more

If hexated dont want to make it he will closed this issue as not planned  ...

**Comment by hexated** [comment]
Captcha
![Screenshot_20231016-030158.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/aae9ad63-6ce6-4d2d-9e6c-46ef15230bd5)

**Comment by aadio7** [comment]
> Captcha ![Screenshot_20231016-030516.png](https://user-images.githubusercontent.com/37908684/275351959-b994ce5b-874f-49a0-93ea-b812cdd41d53.png)

Yaa i know .. someone on git techshreyas has his TechZApi and scrapper which scrap links from mkvcinemas

**Comment by aadio7** [comment]
> Captcha ![Screenshot_20231016-030516.png](https://user-images.githubusercontent.com/37908684/275351959-b994ce5b-874f-49a0-93ea-b812cdd41d53.png)

https://github.com/TechShreyash/MkvCinemas-Scrapper its a scrapper
