### ISSUE TITLE
Sorastream problem

### ISSUE THREAD

**Issue by SaurabhKaperwan** [hexated/cloudstream-extensions-hexated#324]
For every anime it is showing 0 or 1 links only.Yesterday it is working fine.
(Showing multiple links).
![Screenshot_2023-10-16-14-29-08-61_cfa2fd239c8cded9285432912d0e0818.jpg](https://github.com/hexated/cloudstream-extensions-hexated/assets/91174352/91f7b950-219b-45ef-822f-905fe86f1543)

**Comment by hexated** [comment]
![Screenshot_20231016-173336.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/87e049ef-a943-4141-803a-0b829a2726cc)
