### ISSUE TITLE
Hdmovie2 link extraction issue.

### ISSUE THREAD

**Issue by mileymehak77** [hexated/cloudstream-extensions-hexated#330]
I am using cloudstream beta version. After latest update hdmovie 2 link extractor is not working. I have changed the current url for hdmovie 2 in clone site settings but still it's not working.
Tried on cloudstream app too. Same issue found.

**Comment by aadio7** [comment]
Its domain is changed  you have to clone it with new domain and it will work ... https://hdmovie2.pink/

**Comment by aadio7** [comment]
> I am using cloudstream beta version. After latest update hdmovie 2 link extractor is not working. I have changed the current url for hdmovie 2 in clone site settings but still it's not working. Tried on cloudstream app too. Same issue found.

Its domain is changed you have to clone it with new domain and it will work ... https://hdmovie2.pink/
