### ISSUE TITLE
Exstension Request

### ISSUE THREAD

**Issue by Variant1987** [hexated/cloudstream-extensions-hexated#333]
Could you add this provider? It is one of the largest providers in Germany with good quality 

streamkiste.tv

**Comment by Variant1987** [comment]
kinoger.to would also be nice for movies

**Comment by hexated** [comment]
I only add kinoger since Streamkiste have captcha

**Comment by Variant1987** [comment]
@hexated 

Is there no way to disable the captchta at streamkiste? You can choose between streamtape and voe under the stream preview. Maybe you can extract the link here somehow?

I'm asking because this is the only decent German streaming provider for 1080p series
