### ISSUE TITLE
Hdmovie2 link extraction issue not resolved

### ISSUE THREAD

**Issue by mileymehak77** [hexated/cloudstream-extensions-hexated#335]
Thank you for attending to my query promptly. But the problem still remains the same. I know there are other sources that offer hindi content but hdmovie 2 is the only source that makes new content available in a snap, esp hindi dubbed k dramas 🫰🏻. Once again checked both on beta version as well as stable version. It says "No link found".
Edit: I know I can always watch content on their website, but accessing that on smart tv is a bit hectic. That's why I am troubling you with this. 😁

**Comment by hexated** [comment]
Works fine for me,
![Screenshot_20231021-152133.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/6147b11b-3edb-4338-b096-fa8063c01a31)

Try reinstall provider and clear cache.

**Comment by mileymehak77** [comment]
Did what you said and checked again. I found out that the movies work just fine. It's the series where the problem lies. Earlier there was no issue but now it keeps saying "no link found." I am attaching the video here.

https://github.com/hexated/cloudstream-extensions-hexated/assets/145230895/815ee96a-5748-4a53-a6cc-95a1444f0f66



> Works fine for me, ![Screenshot_20231021-152133.png](https://user-images.githubusercontent.com/37908684/277096741-6147b11b-3edb-4338-b096-fa8063c01a31.png)
> 
> Try reinstall provider and clear cache.

**Comment by SaurabhKaperwan** [comment]
It is only working for movies
