### ISSUE TITLE
Extension Request

### ISSUE THREAD

**Issue by krishus96** [hexated/cloudstream-extensions-hexated#341]
Smashy Streams: https://embed.smashystream.com/ | Player D (Hindi)

Anime
https://toonstream.in/
https://animesaga.in/

Thanks in advance :)

**Comment by krishus96** [comment]
Add Player D (Hindi) from https://embed.smashystream.com/ 

![Screenshot 2023-10-29 151956](https://github.com/hexated/cloudstream-extensions-hexated/assets/47269132/1a67530a-3423-49f6-9d7f-bc20aa16a1c6)

**Comment by aadio7** [comment]
> Add Player D (Hindi) from https://embed.smashystream.com/
> 
> ![Screenshot 2023-10-29 151956](https://user-images.githubusercontent.com/47269132/278863260-1a67530a-3423-49f6-9d7f-bc20aa16a1c6.png)

That will be great

**Comment by aadio7** [comment]
@hexated you added the player d?? I saw it after latest update

**Comment by krishus96** [comment]
> @hexated you added the player d?? I saw it after latest update

Yes, it's updated

**Comment by aadio7** [comment]
Cant see toonstream in hexated

**Comment by phisher98** [comment]
Animesaga is also not working says no links and now its not visible in CS
