### ISSUE TITLE
Wrong subtitle in sorastream. And no subtitles in Anichi

### ISSUE THREAD

**Issue by notuser112** [hexated/cloudstream-extensions-hexated#344]
For many sources even though I have selected English as auto select language I get Arabic subtitles. 
When pressed on source to check which subtitle is selected it says no subtitle selected. 
Please fix it. 

And for anichi it shows no subtitles when dub is chosen. But subtitles show up when sub version is chosen(1 or 2). Any chance we can have the subtitles from there in dub as well.

**Comment by hexated** [comment]
What show in Sora. So i can check

**Comment by notuser112** [comment]
Just happened with Blue beetle. Smashy player f 1080p
![Screenshot_20231029_131525_CloudStream Beta](https://github.com/hexated/cloudstream-extensions-hexated/assets/148670935/7212bb60-b004-483b-ab14-cece337451b0)

**Comment by SaurabhKaperwan** [comment]
It also happened with me it automatically select arabic subtitle
