### ISSUE TITLE
Extension Request - German Providers

### ISSUE THREAD

**Issue by Variant1987** [hexated/cloudstream-extensions-hexated#347]
Hello,

here is a list of German providers. Could you add them when you get a chance? It would make the extension very appealing for german users.

[  ] moflix-stream.xyz
[  ] cinemathek.net

**Comment by Variant1987** [comment]
Is there an update on this yet? I understand that you are doing this free of charge and thank you very much again.

Could I donate money to you to speed up the process.

Alternatively, I am familiar with Java, but unfortunately not so good with scraping. Do you have any instructions here that I can use to help?

**Comment by Variant1987** [comment]
Reopen

**Comment by hexated** [comment]
- Choose the best one, ill try to add when i'm free.
- i don't take donation
- https://github.com/Blatzar/scraping-tutorial very good tutorial for beginner

**Comment by Variant1987** [comment]
Hi,

Thanks for the link, I'll have a look. The best website for this would be https://hdfilme.bar

**Comment by Variant1987** [comment]
The best one would be: https://moflix-stream.xyz

It also hast a Lot of metadata about the movies, shows

**Comment by Variant1987** [comment]
If you need some help with coding, here is a template of another app for the site

https://github.com/streamxstream/plugin.video.xstream/blob/nexus/sites/moflix-stream.py
