### ISSUE TITLE
Anichi source error

### ISSUE THREAD

**Issue by KillerDogeEmpire** [hexated/cloudstream-extensions-hexated#350]
most anichi sources don't work, sometimes loads, and most of the time says no links found, re entering the app a few times makes it work again, but leaving the show makes the no links found error show up again

**Comment by KillerDogeEmpire** [comment]
also most sources are missing, last time before update there were way more servers, no I only get 3

**Comment by hexated** [comment]
Still works fine for me
![Screenshot_20231031-234857.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/112b2919-ede6-426b-8d92-23606c93f3df)
