### ISSUE TITLE
Bug:Smashy link missing

### ISSUE THREAD

**Issue by aadio7** [hexated/cloudstream-extensions-hexated#365]
Smashy (all players) links is not showing in movies and series please fix this issue

.. or maybe some of smashy player not showing up like player D(i have only found link of smashy player F)

**Comment by SaurabhKaperwan** [comment]
Same issue

**Comment by krishus96** [comment]
yes.

**Comment by aadio7** [comment]
@hexated after the end of vega... please add player d(hindi) again to sora

**Comment by aadio7** [comment]
@hexated broo i cant see player d still....
