### ISSUE TITLE
Why this is showing no link 

### ISSUE THREAD

**Issue by Adi432144** [hexated/cloudstream-extensions-hexated#37]
I want to watch Muhteşem Yüzyıl in Sora stream but sorastream showing no link ![Screenshot_2022-11-30-12-49-09-57_cfa2fd239c8cded9285432912d0e0818.jpg](https://user-images.githubusercontent.com/74503284/204732298-e9658ca4-f304-4dda-ba74-8af9c9ccb5a5.jpg)

But the second season of Muhteşem Yüzyıl is working fine

**Comment by hexated** [comment]
Not all video can be play. Because Its use tmdb
