### ISSUE TITLE
Movierulzhd addon not working 

### ISSUE THREAD

**Issue by MixSens** [hexated/cloudstream-extensions-hexated#370]
The movierulzhd site has got multiple streams for a title but the app only checks for the first stream and exits if the strean is invalid.

Requesting the repo devs to update the repo to be able to check for all the available links of a title and play it

**Comment by Rockymar11** [comment]
Movierulzhd not working please fix it

**Comment by abbae07** [comment]
Movierulzhd not loading any links for the titles shown ..please fix when you are free..
