### ISSUE TITLE
Movierulzhd no link found 

### ISSUE THREAD

**Issue by Rockymar11** [hexated/cloudstream-extensions-hexated#374]
Hey dev can you fix movierulzhd please website working fine please 🥺 can you fix it

**Comment by Rockymar11** [comment]
Still it's not working why did you closed ticket

**Comment by abbae07** [comment]
> Still it's not working why did you closed ticket

Hey its loading for me ..try clearing cache of app and then restart and I also set the dns to quad9..

**Comment by Rockymar11** [comment]
> > Still it's not working why did you closed ticket
> 
> Hey its loading for me ..try clearing cache of app and then restart and I also set the dns to quad9..

It's working now
