### ISSUE TITLE
Feature sorastream

### ISSUE THREAD

**Issue by owencz1998** [hexated/cloudstream-extensions-hexated#38]
Would it be possible to add these sections for Netflix ect for sorastream it would look nice 👍 

![Screenshot_20221202_172839_SunStream Beta.jpg](https://user-images.githubusercontent.com/96526481/205351014-7a3e907b-2fd5-4852-ad3d-d10f163759f0.jpg)

**Comment by shubham01015** [comment]
Yep.... It will be great if it's comes
