### ISSUE TITLE
Bug: Vega is hit & miss for webseries

### ISSUE THREAD

**Issue by aadio7** [hexated/cloudstream-extensions-hexated#380]
Vega and dotmovies(gofille&vcloud)  is perfectly working for movies whereas it is hit and miss for webseries\shows in vega as well as dotmovies i.e. For some webseries it show link whereas for others(a lot of famous web series) it don't show

**Comment by hexated** [comment]
What shows?

**Comment by aadio7** [comment]
> What shows?

A lot webseries ..i can't name everyone ..like Blanca,aarya,Lucifer,etc ..old as well as new webseries

**Comment by aadio7** [comment]
> What shows?
This is one of the example there are many
![Screenshot_20231116-180404_CloudStream Beta](https://github.com/hexated/cloudstream-extensions-hexated/assets/147267681/8a4ab5f1-9adc-44ac-a9a3-3bfc72c8fbcb)

![Screenshot_20231116-180327_Chrome](https://github.com/hexated/cloudstream-extensions-hexated/assets/147267681/caa86a78-1512-46de-8525-7a27057cbeec)
