### ISSUE TITLE
help in loading links

### ISSUE THREAD

**Issue by Thorodinson1** [hexated/cloudstream-extensions-hexated#381]
iam trying scrape a site but i cant load links but it is iframe as direct source links and also there is a streamtape link so can help me 

import com.lagradost.cloudstream3.*
import com.lagradost.cloudstream3.LoadResponse.Companion.addActors
import com.lagradost.cloudstream3.mvvm.safeApiCall
import com.lagradost.cloudstream3.utils.ExtractorLink
import com.lagradost.cloudstream3.utils.AppUtils.parseJson
import com.lagradost.cloudstream3.utils.AppUtils.toJson
import com.lagradost.cloudstream3.utils.loadExtractor
import com.lagradost.cloudstream3.utils.*
import org.jsoup.Jsoup
import org.jsoup.nodes.Element
import java.util.*

    override suspend fun loadLinks(
        data: String,
        isCasting: Boolean,
        subtitleCallback: (SubtitleFile) -> Unit,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        val document = app.get(data).document
        document.select("video #video").map { res ->
            callback.invoke(
                ExtractorLink(
                    this.name,
                    this.name,
                    res.attr("href")
                        .replace(Regex("\\?download\\S+.mp4&"), "?") + "&rnd=${Date().time}",
                    referer = data,
                    quality = Regex("([0-9]+p),").find(res.text())?.groupValues?.get(1)
                        .let { getQualityFromName(it) },
                    headers = mapOf("Range" to "bytes=0-"),
                )
            )
        }

        return true
    }

}

**Comment by hexated** [comment]
try this:

```kt
override suspend fun loadLinks(
        data: String,
        isCasting: Boolean,
        subtitleCallback: (SubtitleFile) -> Unit,
        callback: (ExtractorLink) -> Unit
    ): Boolean {

        val iframe = app.get(data).document.select("div.responsive-player iframe").attr("src")
        
        if (iframe.startsWith(mainUrl)) {
            val video = app.get(iframe, referer = data).document.select("video source").attr("src")
            callback.invoke(
                ExtractorLink(
                    this.name,
                    this.name,
                    video,
                    "$mainUrl/",
                    Qualities.Unknown.value,
                    INFER_TYPE,
                    headers = mapOf(
                        "Range" to "bytes=0-",
                    ),
                )
            )
        } else {
            loadExtractor(iframe, "$mainUrl/", subtitleCallback, callback)
        }

        return true
    }
```
