### ISSUE TITLE
Uhdmovies links not showing up

### ISSUE THREAD

**Issue by warchild679** [hexated/cloudstream-extensions-hexated#386]
Im still not seeing any Uhdmovies links its been 4 days Ive asked two people from discord to test to see Uhdmovies links is showing on Sorastream an they too not seeing Uhdmovies link.Theres no error what should I do,do a fresh install,clear data or install the stable version I have the https on google and Im using no vpn.

**Comment by hexated** [comment]
Try VPN and use pre. If still doesnt works. No luck

**Comment by aadio7** [comment]
> Try VPN and use pre. If still doesnt works. No luck. Also its not issue with provider. Check #380

@hexated @warchild679 this issue can be solved by using aniyomi uhd ext in CS...but Vega has no separate Ext.. Maybe @hexated you can work on #286

**Comment by Rayforest** [comment]
> Try VPN and use pre. If still doesnt works. No luck. Also its not issue with provider. Check #380

@hexated does UHDmovies work for you in internal player? It only buffers forever for me, even with vpn. It works in VLC though. I wonder what changed in the internal player that made uhdmovies unwatchable. Maybe it is my device

**Comment by aadio7** [comment]
> > Try VPN and use pre. If still doesnt works. No luck. Also its not issue with provider. Check #380
> 
> @hexated does UHDmovies work for you in internal player? It only buffers forever for me, even with vpn. It works in VLC though. I wonder what changed in the internal player that made uhdmovies unwatchable. Maybe it is my device

It wont work in internal player .. only can work  in vlc..  uhdm aniyomi can work in internal player
