### ISSUE TITLE
server anime is missing

### ISSUE THREAD

**Issue by owengofficial** [hexated/cloudstream-extensions-hexated#387]
bang server anime di sorastream yang dulu hilang jadi kalau mau putar anime lawas ga bisa, kalau anime judul baru kadang ada tapi pake server baru mereka,saya lupa nama server yang dulu padahal hampir lengkap itu putar anime lawas atau baru.

**Comment by hexated** [comment]
Pakai provider Indonesia aj.. maintain nya susah. Syg kalo nggk dipake
