### ISSUE TITLE
SFMovies remote error

### ISSUE THREAD

**Issue by SaurabhKaperwan** [hexated/cloudstream-extensions-hexated#389]

**Comment by aadio7** [comment]
> _No description provided._

Server was down.. Now server is live . But still sfmovies show error

**Comment by SaurabhKaperwan** [comment]
@IndusAryan This pr is not related to this issue.

**Comment by aadio7** [comment]
> @IndusAryan This pr is not related to this issue. SFMovies means streamflix not showflix

Showflix is by likdev.. So here sf means streamflix
