### ISSUE TITLE
Bug:Vega and Dotmovs are no longer visible at all

### ISSUE THREAD

**Issue by aadio7** [hexated/cloudstream-extensions-hexated#393]
The link of Vega and Dotmovies is not showing for any movies/series... there is some error or integeration issue.. it is not showing vega link in any movie/series(earlier for which it was showing)

**Comment by hexated** [comment]
Both are adding cloudflare. End of era

**Comment by aadio7** [comment]
> Both are adding cloudflare. End of era

so does cloudfare is added to vcloud only.. since there are gdtot links also
