### ISSUE TITLE
Site request: (vega alternative)

### ISSUE THREAD

**Issue by aadio7** [hexated/cloudstream-extensions-hexated#397]
https://moviesmod.shop/.. This site

**Comment by aadio7** [comment]
@hexated is it possible???

**Comment by hexated** [comment]
They have cloudflare

**Comment by SaurabhKaperwan** [comment]
@hexated in aniyomi or tachiyomi whenever a website raised cloudfare we can bypass it by changing the user agent string. I'am just curious if we have this feature of changing user agent string in cs3 can it solve the vegamovies cloudfare problem.

**Comment by aadio7** [comment]
> @hexated in aniyomi or tachiyomi whenever a website raised cloudflare we can bypass it by changing the user agent string. I'am just curious if we have this feature of changing user agent string in cs3 can it solve the vegamovies cloudflare problem.

I mean i have tried this in uhdm aniyomi but it only shows things when click it to play it will show no links found

**Comment by SaurabhKaperwan** [comment]
> > @hexated in aniyomi or tachiyomi whenever a website raised cloudflare we can bypass it by changing the user agent string. I'am just curious if we have this feature of changing user agent string in cs3 can it solve the vegamovies cloudflare problem.
> 
> I mean i have tried this in uhdm aniyomi but it only shows things when click it to play it will show no links found

It is bypassing cloudflare in uhdm and I think no link issue is not related with cloudflare

**Comment by aadio7** [comment]
> > > @hexated in aniyomi or tachiyomi whenever a website raised cloudflare we can bypass it by changing the user agent string. I'am just curious if we have this feature of changing user agent string in cs3 can it solve the vegamovies cloudflare problem.
> > 
> > 
> > I mean i have tried this in uhdm aniyomi but it only shows things when click it to play it will show no links found
> 
> It is bypassing cloudflare in uhdm and I think no link issue is not related with cloudflare
Does you have the no link issue?? ..since no link issue comes after uhdm added cloudflare

**Comment by hexated** [comment]
> @hexated in aniyomi or tachiyomi whenever a website raised cloudflare we can bypass it by changing the user agent string. I'am just curious if we have this feature of changing user agent string in cs3 can it solve the vegamovies cloudflare problem.

It possible if i make separate provider, but not in sora

**Comment by aadio7** [comment]
> > @hexated in aniyomi or tachiyomi whenever a website raised cloudflare we can bypass it by changing the user agent string. I'am just curious if we have this feature of changing user agent string in cs3 can it solve the vegamovies cloudflare problem.
> 
> It possible if i make separate provider, but not in sora

Its good that if you like to create vega nd uhdm seperate provider
