### ISSUE TITLE
Site request:bollymaza(dotmovie alternative)

### ISSUE THREAD

**Issue by aadio7** [hexated/cloudstream-extensions-hexated#398]
https://ww3.bollymaza.click/ ... this a great alternative to dotmovies ... please try once

**Comment by IndusAryan** [comment]
it is a downloading site plus it has captcha too

**Comment by aadio7** [comment]
> it is a downloading site plus it has captcha too

For Vega .. moviesmod or any other similar website will be good...large library and dual audio

**Comment by aadio7** [comment]
> it is a downloading site plus it has captcha too

what will be the alternative for indian content now after dotmovie end
