### ISSUE TITLE
Add smashystream player d

### ISSUE THREAD

**Issue by SaurabhKaperwan** [hexated/cloudstream-extensions-hexated#404]
![Screenshot_2023-11-27-07-34-49-57_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/hexated/cloudstream-extensions-hexated/assets/91174352/30a24205-3f05-41a2-bcbf-a53b45b81dd8)

**Comment by IndusAryan** [comment]
what does this pr did then #346

**Comment by SaurabhKaperwan** [comment]
It is working before now it is not working
