### ISSUE TITLE
Uhdmovies and Vegamovies

### ISSUE THREAD

**Issue by Jarvis636** [hexated/cloudstream-extensions-hexated#425]
Hi Ive noticed for the past 3-4 days Uhdmovies and vegamovies links not showing up on Sorastream like before hoping for a fix as soon as possible.

**Comment by IndusAryan** [comment]
because uhd movies added cloudflare protection

**Comment by aadio7** [comment]
> because uhd movies added cloudflare protection

Vega and for movie also not showing.. Only for some old content Vega showing...can adding Vega and uhdm as separate provide in hexated with some bypass thing will help??

**Comment by Jarvis636** [comment]
So there wont be a possibility this will be fixed

**Comment by aadio7** [comment]
> So there wont be a possibility this will be fixed

Aniyomi fixed uhdm .. And i think vega removed cloudflre

**Comment by Jarvis636** [comment]
But will this bug be fixed on Sorastream it's still my go to I just need Uhdmovies to be fixed.

**Comment by aadio7** [comment]
u added as new provider.. Or as source in sora??
