### ISSUE TITLE
Site Request

### ISSUE THREAD

**Issue by phisher98** [hexated/cloudstream-extensions-hexated#440]
No Site working if already available then also it will be Good if these can be added 

https://allmovieland.fun/
https://www.animesaga.in/

**Comment by IndusAryan** [comment]
allmovieland from likdev repo works, use proton vpn , cant guarantee all streams to work but majority work

**Comment by phisher98** [comment]
What about https://www.animesaga.in/ ? Aniyomi extension is not working

**Comment by IndusAryan** [comment]
already requested in #341
