### ISSUE TITLE
Issue in sorastream

### ISSUE THREAD

**Issue by SaurabhKaperwan** [hexated/cloudstream-extensions-hexated#444]
Most of the time when I click on the copy link button for a movie or show it just keep loading and continuously using internet like 3-4 MB per second and not returning any link.
After some time app is crashing.

This issue is only happening in sorastream not in sorastream lite.

I think this issue is related with UHDMovies or vegamovies.

**Comment by aadio7** [comment]
Yes same here

**Comment by hexated** [comment]
> > two
> 
> I think it is related with UHDMovies or vegamovies because whenever I play a movie if UHDMovies or vegamovies link present their then it is consuming data with 10MB per second even if I'am playing different stream and after some time app is crashing but when UHDMovies is not present their then it is working fine.

Can you test again? Reinstall provider first

**Comment by SaurabhKaperwan** [comment]
Tried reinstalling sorastream but issue is still their.

![Screenshot_2023-12-11-18-59-30-43_cfa2fd239c8cded9285432912d0e0818.jpg](https://github.com/hexated/cloudstream-extensions-hexated/assets/91174352/b38bfc82-81a7-45bc-9b34-cb5752238f9e)

**Comment by SaurabhKaperwan** [comment]
If play video then it is using data like 10MB per second and after some app crashing. Many people in discoed have same problem.

**Comment by IndusAryan** [comment]
chech this thread 
https://github.com/recloudstream/cloudstream/issues/809
