### ISSUE TITLE
https://madstream.live/ can we add this website very good for live 

### ISSUE THREAD

**Issue by phisher98** [hexated/cloudstream-extensions-hexated#446]
https://madstream.live/

**Comment by phisher98** [comment]
if possible and will not be a complex one then only

**Comment by aadio7** [comment]
+1 ...

**Comment by aadio7** [comment]
> if possible and will not be a complex one then only

Only tata play working for me... others are just loading

**Comment by hexated** [comment]
Close due to site doesnt work..
