### ISSUE TITLE
[SoraStream] New Provider's

### ISSUE THREAD

**Issue by OshekharO** [hexated/cloudstream-extensions-hexated#45]
1. https://onionflix.org
2. https://hub.smashystream.com
3. https://autoembed.to
4. https://popmovies.top
5. https://azseries.org
6. https://bmovies.cloud
7. https://fastmovies.to
8. https://seapi.link/?type=imdb&id=tt15325794&max_results=1

**Comment by OshekharO** [comment]
Close?

**Comment by hexated** [comment]
Yeah, Most of them already be implemented,
