### ISSUE TITLE
Source request: toonstream

### ISSUE THREAD

**Issue by aadio7** [hexated/cloudstream-extensions-hexated#451]
#341 requested for https://toonstream.in/.. but i cant find it in hexated..
Please add it

**Comment by dontseehereStopMotion** [comment]
Animedekho is a far better website

**Comment by dontseehereStopMotion** [comment]
[AnimeDekhoProvider.zip](https://github.com/hexated/cloudstream-extensions-hexated/files/13700466/AnimeDekhoProvider.zip)
 
It was working like 2 months ago but now you have to go to their site and press 'Skip Ads' once to use it in app, and also their vidxtream site added something that even WebViewResolver cant go past it
