### ISSUE TITLE
Source request : animedekho

### ISSUE THREAD

**Issue by ShankarKSH001** [hexated/cloudstream-extensions-hexated#456]
Site : https://animedekho.com/
Anime and cartoons content in multi audio.

**Comment by hexated** [comment]
![Screenshot_20231219-025536.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/374a82c3-545a-43c3-820f-52be0b0d0872)

**Comment by ShankarKSH001** [comment]
Turn off vpn or adblocker bro.

**Comment by hexated** [comment]
Still doesn't work. Seems like they block my country. I'll close this for now
