### ISSUE TITLE
https://playdesi.net

### ISSUE THREAD

**Issue by phisher98** [hexated/cloudstream-extensions-hexated#457]
If it can be added in Sorastream or seprate any will work 
https://playdesi.net

Thamks

**Comment by aadio7** [comment]
> If it can be added in Sorastream or seprate any will work https://playdesi.net
> 
> Thamks

Quality is not good.. 720p webrip quality..

**Comment by phisher98** [comment]
Ok buddy

**Comment by phisher98** [comment]
@aadio7 are you on discord ?

**Comment by aadio7** [comment]
> @aadio7 are you on discord ?

Yeahhh...
