### ISSUE TITLE
Dead/missing sources

### ISSUE THREAD

**Issue by notuser112** [hexated/cloudstream-extensions-hexated#473]
Blackvid no longer shows any links. 
Aoneroom api only shows English movies and tv-shows. It has Bollywood stuff and cartoons/anime as well which are missing. 
Ling and dbgo no longer show any links. 
Smashy player only works for some shows. Smashy hardly works for movies now. 
Navy and moment also don't show any links.

**Comment by hexated** [comment]
Blackvid changed with febbox
