### ISSUE TITLE
Kindly commit your contributions to: #FreePalestine🇵🇸 Support Kit

### ISSUE THREAD

**Issue by aminblm** [hexated/cloudstream-extensions-hexated#476]
Here is the link to the repository, I will add your website to the list: [#FreePalestine🇵🇸 Support Kit](https://github.com/aminblm/awesome-free-palestine-support-kit)

**Comment by IndusAryan** [comment]
what does this achieves , i mean what will happen? btw i also from india full sapot to palestine innocents and innocents of both all world countries. i also stand with innocent people but not leadership that is sunbathing in qatar.

**Comment by aadio7** [comment]
> what does this achieves , i mean what will happen? btw i also from india full sapot to innocents of both country and innocents of all countries. i also stand with innocent people but not leadership that is sunbathing in qatar.

100% true bro...

**Comment by aminblm** [comment]
More awareness especially from the social side 🌍📣 and keep your non-encouraging comments to yourself 🤫, we don't want this kind of energy in here ❌⚡. The killing of the children must stop 🛑👶 and we are ready to take concrete steps in that regards 🚀🤝. Even a 0.001% progress and 1 more person reached is better than sitting idle 🛋️🚫 and stopping the resistance ✊🌟.

**Comment by IndusAryan** [comment]
yes agree 💯👍, full standing to innocents 🔥 of all countries involved, this issue (marked as offtopic) can be closed now 🥳🫡.
