### ISSUE TITLE
https://allmovieland.fun/

### ISSUE THREAD

**Issue by phisher98** [hexated/cloudstream-extensions-hexated#481]
Likedev Plugin is not maintained anymore and its working on websitge but not in CS also giving 2002 error Kindly check if it can be added in Hex or fixed ?

**Comment by SaurabhKaperwan** [comment]
Allmovieland is working fine just use external dns

**Comment by SaurabhKaperwan** [comment]
Allmovieland is working fine just use external dns

**Comment by phisher98** [comment]
I have tried with Cloudflare/Google/Adguard DNS options but if i use VPN then only and sometimes it does work without it but not consistent

**Comment by aadio7** [comment]
> I have tried with Cloudflare/Google/Adguard DNS options but if i use VPN then only and sometimes it does work without it but not consistent

Yaa thats site problrm

**Comment by SaurabhKaperwan** [comment]
I'am using nextdns and it is working for me almost every time

**Comment by phisher98** [comment]
Ok will try it once

**Comment by aadio7** [comment]
> Ok will try it once

Its added in sora

**Comment by phisher98** [comment]
@aadio7 I can see it in code but not in App Can i get your discord name on CS Discord ?

**Comment by aadio7** [comment]
> @aadio7 I can see it in code but not in App Can i get your discord name on CS Discord ?

Bruh.. you can see the links for any movie in sora. its contains allmovieland also

**Comment by phisher98** [comment]
@aadio7 can you give me your Discord i want to chat with you on this 

When I am checking source there is no source available from allmovieland
![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/153359846/9329681f-6d3c-42bd-aa37-aa19d960dd0a)

**Comment by aadio7** [comment]
> @aadio7 can you give me your Discord i want to chat with you on this
> 
> When I am checking source there is no source available from allmovieland ![image](https://private-user-images.githubusercontent.com/153359846/293576251-9329681f-6d3c-42bd-aa37-aa19d960dd0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTIxMDksIm5iZiI6MTcwNDExMTgwOSwicGF0aCI6Ii8xNTMzNTk4NDYvMjkzNTc2MjUxLTkzMjk2ODFmLTZkM2MtNDJiZC1hYTM3LWFhMTlkOTYwZGQwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxMjIzMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDU2Yjc4ZDQyN2M2Nzc5NzhiMWE3M2JmNTkyNzljZDFjNzY5OGQyYjA1ODg5NmRhMzFlZGEzZGNiNGFlZTkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rU5NkVpAmf7Br9IePAgcE0nQ85NOel8imMyVEpLhFXY)

freak_.adi - my discord 
Check loki and see if you can see the source.... cause you cant see the source in everything

**Comment by phisher98** [comment]
Yup Its Visible in Loki
