### ISSUE TITLE
Nekopoi, otakudesu site issue

### ISSUE THREAD

**Issue by iamtaufik** [hexated/cloudstream-extensions-hexated#482]
Can't displaying any results

**Comment by hexated** [comment]
Change DNS or use VPN

**Comment by iamtaufik** [comment]
![Screenshot_2023-12-30-00-50-42-365_com lagradost cloudstream3 prerelease](https://github.com/hexated/cloudstream-extensions-hexated/assets/80101639/47576aa6-b287-413f-9d53-dd31f4e52012)

If use DNS got error like this

**Comment by hexated** [comment]
Hanime?
