### ISSUE TITLE
Regarding AnimeSaga

### ISSUE THREAD

**Issue by LiReNa00** [hexated/cloudstream-extensions-hexated#483]
So yea site dont load there is timeout the issue is already open I know....
but even when it was working fine the m3u8 url wont load umm so the thing is I created an api in python which might be helpful and also I will be thankful if u integrate this api into the extension as I really dont know much kotlin and I want to watch stuff from animesaga.
here is url of the api https://teplix.vercel.app/docs

**Comment by hexated** [comment]
Ill close this now since animesaga start working. Feel free to open it again
