### ISSUE TITLE
how to play akamaicdn m3u8

### ISSUE THREAD

**Issue by himanshu8443** [hexated/cloudstream-extensions-hexated#490]
plz, can you tell me how to play master.txt in the HDmovies2 source? I am trying but it's not loading.

https://akamaicdn.life/m3u8/1/e5e580bb7e6f5e01ecf1be2c21a834e7/master.txt?s=1&cache=1

**Comment by hexated** [comment]
It needs special header to play.
Check this : https://github.com/recloudstream/cloudstream/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Flagradost%2Fcloudstream3%2Fextractors%2FChillx.kt#L55-L61
