### ISSUE TITLE
1080p not showing for vega

### ISSUE THREAD

**Issue by heliosII** [hexated/cloudstream-extensions-hexated#491]
earlier vega used to show 4k as well as 1080p links if the content is avail in both reso and if its only avail in 1080p then shows 1080p but pnow if the content on website is 4k as well as 1080p then its only show the 4k link not the 1080p link and if content avail in 1080p then its acts normally shows 1080p.. that means after update vega only showing the highest resolution link.. (my firestick cant play 4k reso)
![cs](https://github.com/hexated/cloudstream-extensions-hexated/assets/155451775/4e5eecb3-f3a8-4a61-8ee6-04e102c7cebd)
![vega](https://github.com/hexated/cloudstream-extensions-hexated/assets/155451775/6939a645-9be9-4f0e-ac3b-7ec4958b749b)

**Comment by SaurabhKaperwan** [comment]
Same issue sometimes it only shows 4k links and I watch movies on phone and on phone 1080p is more than enough.

**Comment by heliosII** [comment]
> Same issue sometimes it only shows 4k links and I watch movies on phone and on phone 1080p is more than enough.

always shows 4k if 4k reso is avail for that content
