### ISSUE TITLE
animeSAGA is not working properly 

### ISSUE THREAD

**Issue by kusokohei** [hexated/cloudstream-extensions-hexated#492]
![Screenshot_2024-01-04-02-38-19-810_com lagradost cloudstream3](https://github.com/hexated/cloudstream-extensions-hexated/assets/140593165/590282b7-1139-4f5d-8f1a-c95cfcebdadf)

animeSAGA gives a no links found response even with a VPN 
Dev , please fix this

**Comment by hexated** [comment]
Works fine for me,
![Screenshot_20240104-062353.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/8f1443eb-c883-46bc-8508-e72090b717b8)

Use pre or update your app
