### ISSUE TITLE
Time4tv remote error for some channel

### ISSUE THREAD

**Issue by heliosII** [hexated/cloudstream-extensions-hexated#494]
In time4tv ..some Daddy hd channels like tnt usa, laliga tv, viaplay,espn,etc give remote error.  Whereas the same stream play on site perfectly.  i have seen the provide url is https://time4tv.stream/ (site doesnt open) .  But all stream are from https://dlhd.sx/stream  (daddyhd site) opening and working fine. So maybe you can directly make https://dlhd.sx/ as povider or url.  Maybe it will solve the problem

**Comment by heliosII** [comment]
@hexated is it okay or should i open a seperate source request for https://dlhd.sx/. As time4tv not working fine

**Comment by hexated** [comment]
Its okay, no need to open new issue

**Comment by heliosII** [comment]
> Its okay, no need to open new issue

Could you add all player for a stream  . Which we change from source as like smashy. Since some stream have diff channel as player1,2... Thanks

**Comment by aadio7** [comment]
@hexated thanks a lot sir for this.
