### ISSUE TITLE
Extract movies from this app

### ISSUE THREAD

**Issue by SaurabhKaperwan** [hexated/cloudstream-extensions-hexated#495]
www.dooflixapk.com

It have large Indian and Hollywood content in 1080p quality.
![Screenshot_2024-01-05-05-56-06-73_005220665292bc3803e84a62569b7eed.jpg](https://github.com/hexated/cloudstream-extensions-hexated/assets/91174352/4081ea40-a9d8-42e5-b7f5-daa008938fa5)

**Comment by heliosII** [comment]
uses hdmovie2 ig. i used to use this. its name was hdmovie2 then dooflix

**Comment by phisher98** [comment]
HDMovie2 is already present in this repo

**Comment by SaurabhKaperwan** [comment]
> HDMovie2 is already present in this repo

Their are some movies present which are not in hdmovie

**Comment by heliosII** [comment]
> > HDMovie2 is already present in this repo
> 
> Their are some movies present which are not in hdmovie

Idk but i think its quality is not that good like sfmovies

**Comment by hexated** [comment]
Hdmovie2 and allmovieland combine
