### ISSUE TITLE
Animedekho movie not working and idk you make anime saga or not you make then animesaga serchinh not working fix. fixhttps://bollyflix.fans/ if you can add this website 

### ISSUE THREAD

**Issue by Mrunknow3** [hexated/cloudstream-extensions-hexated#496]

**Comment by heliosII** [comment]
> _No description provided._

Animesaga search is working. In search option make sure to select or enable the anime and cartoon option in search below the search bar. and please dont open multiple in one issue

**Comment by hexated** [comment]
Animedekho needs to bypass ads once/day

**Comment by heliosII** [comment]
> Animedekho needs to bypass ads once/day

Ik but animedekho movie problem is there. I also bypass ad
