### ISSUE TITLE
Source missing

### ISSUE THREAD

**Issue by ShankarKSH001** [hexated/cloudstream-extensions-hexated#497]
In sorastream 2 source are missing.
1. Streamruby
2.  Filelions

Can you pls add this source again because these two are the only best source for watching in tamil language.

**Comment by heliosII** [comment]
> 1. Streamruby

Streamruby shows but in very less content

**Comment by ShankarKSH001** [comment]
> > 1. Streamruby
> 
> Streamruby shows but in very less content

I watched squid game series on streamruby & filelions source but now it not showing.

**Comment by heliosII** [comment]
@hexated bro which site is streamruby source

**Comment by ShankarKSH001** [comment]
> @hexated bro which site is streamruby source

Multiple source available in 'Sorastream' with streamruby.
Streamruby mostly available in webseries contents.

**Comment by heliosII** [comment]
> > @hexated bro which site is streamruby source
> 
> Multiple source available in 'Sorastream' with streamruby. Streamruby mostly available in webseries contents.

Most of the sources have one site associated like .. vega with gofile/vcloud .. rstream for remote stream,flixmy alpha with flimy site

**Comment by ShankarKSH001** [comment]
> > > @hexated bro which site is streamruby source
> > 
> > 
> > Multiple source available in 'Sorastream' with streamruby. Streamruby mostly available in webseries contents.
> 
> Most of the sources have one site associated like .. vega with gofile/vcloud .. rstream for remote stream,flixmy alpha with flimy site

Yes very few contents only with these streamruby, filelions, SFmovies1080p sources. Iam mostly used these 3 sources for watch in tamil.
