### ISSUE TITLE
Filmxy Link Issue

### ISSUE THREAD

**Issue by Jeenesh7** [hexated/cloudstream-extensions-hexated#499]
Filmxy links aren't appearing anymore maybe because the site "filmxy.vip" isn't working atm. However, there's another site which is completely the same "filmsxy.vip". So can the new one be used instead? Thanks in advance.

**Comment by hexated** [comment]
Still working for me
![Screenshot_20240106-210617.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/a6bab6c9-6011-41ab-b297-84042d1220d7)
