### ISSUE TITLE
Animedekho not working now fix 

### ISSUE THREAD

**Issue by Mrunknow3** [hexated/cloudstream-extensions-hexated#503]
![Screenshot_2024-01-07-16-29-20-603_com.lagradost.cloudstream3.prerelease.jpg](https://github.com/hexated/cloudstream-extensions-hexated/assets/154901963/8ca96856-43d1-40f7-ae80-d2d7a5f5fdbc)

**Comment by heliosII** [comment]
Its working for me

**Comment by phisher98** [comment]
![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/153359846/68c2418f-9b8c-4bea-b37b-5d388bcb758b)
Working fine

**Comment by Mrunknow3** [comment]
Now working fine but 1 hours probably not work

**Comment by heliosII** [comment]
> Now working fine but 1 hours probably not work

Close this issue then

**Comment by ShankarKSH001** [comment]
> ![image](https://private-user-images.githubusercontent.com/153359846/294761384-68c2418f-9b8c-4bea-b37b-5d388bcb758b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjkxNTMsIm5iZiI6MTcwNDcyODg1MywicGF0aCI6Ii8xNTMzNTk4NDYvMjk0NzYxMzg0LTY4YzI0MThmLTliOGMtNGJlYS1iMzdiLTVkMzg4YmNiNzU4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2UxMjVjY2IwZDBkMmEwZjBjOTNlNDY5M2YyZjNlNGY2YjQ5MjE5NTAwYjYxYWU4ZDIyNDVhOWZjZTBkMDE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8zgDtqh1sfHlVNhWGZFFe33YQ1CQSTgNe-lmwEsfiaw) Working fine
Bro how you use cloudstream in pc ?
Any emulators

**Comment by heliosII** [comment]
> > ![image](https://private-user-images.githubusercontent.com/153359846/294761384-68c2418f-9b8c-4bea-b37b-5d388bcb758b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjkxNTMsIm5iZiI6MTcwNDcyODg1MywicGF0aCI6Ii8xNTMzNTk4NDYvMjk0NzYxMzg0LTY4YzI0MThmLTliOGMtNGJlYS1iMzdiLTVkMzg4YmNiNzU4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2UxMjVjY2IwZDBkMmEwZjBjOTNlNDY5M2YyZjNlNGY2YjQ5MjE5NTAwYjYxYWU4ZDIyNDVhOWZjZTBkMDE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8zgDtqh1sfHlVNhWGZFFe33YQ1CQSTgNe-lmwEsfiaw) Working fine
> > Bro how you use cloudstream in pc ?
> > Any emulators?

Not emulator .. windows 11 has capability to run android app..

**Comment by ShankarKSH001** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/153359846/294761384-68c2418f-9b8c-4bea-b37b-5d388bcb758b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjkxNTMsIm5iZiI6MTcwNDcyODg1MywicGF0aCI6Ii8xNTMzNTk4NDYvMjk0NzYxMzg0LTY4YzI0MThmLTliOGMtNGJlYS1iMzdiLTVkMzg4YmNiNzU4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2UxMjVjY2IwZDBkMmEwZjBjOTNlNDY5M2YyZjNlNGY2YjQ5MjE5NTAwYjYxYWU4ZDIyNDVhOWZjZTBkMDE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8zgDtqh1sfHlVNhWGZFFe33YQ1CQSTgNe-lmwEsfiaw) Working fine
> > > Bro how you use cloudstream in pc ?
> > > Any emulators?
> 
> Not emulator .. windows 11 has capability to run android app..

Oh idk that thanks for reply bruh 👐.

**Comment by heliosII** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/153359846/294761384-68c2418f-9b8c-4bea-b37b-5d388bcb758b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MjkxNTMsIm5iZiI6MTcwNDcyODg1MywicGF0aCI6Ii8xNTMzNTk4NDYvMjk0NzYxMzg0LTY4YzI0MThmLTliOGMtNGJlYS1iMzdiLTVkMzg4YmNiNzU4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQxNTQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2UxMjVjY2IwZDBkMmEwZjBjOTNlNDY5M2YyZjNlNGY2YjQ5MjE5NTAwYjYxYWU4ZDIyNDVhOWZjZTBkMDE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8zgDtqh1sfHlVNhWGZFFe33YQ1CQSTgNe-lmwEsfiaw) Working fine
> > > > Bro how you use cloudstream in pc ?
> > > > Any emulators?
> > 
> > 
> > Not emulator .. windows 11 has capability to run android app..
> 
> Oh idk that thanks for reply bruh 👐.

I want to talk to you on discord .. could you share your github user
