### ISSUE TITLE
Remote error 

### ISSUE THREAD

**Issue by heliosII** [hexated/cloudstream-extensions-hexated#504]
Idk what happens but now time4tv giving remote error since 24 hours for some channels and some channels its running fine whereas on site everything is working fine.. its like it was working for all channels in starting then start showing remote error for some channel since 24 hour .. i tried dns and vpn but nothing happen

![Screenshot_20240107-173933_CloudStream Beta](https://github.com/hexated/cloudstream-extensions-hexated/assets/155451775/bd5dd9e3-3778-4db4-9d9d-d107da97db84)
![Screenshot_20240107-173852_Chrome](https://github.com/hexated/cloudstream-extensions-hexated/assets/155451775/934a5458-aa01-488a-a6ce-1ffe315fa10e)

**Comment by heliosII** [comment]
Similar happen #494 but it automatically got solved in 5 hours after i open #494

**Comment by heliosII** [comment]
@hexated 
![Screenshot_20240107-201739_Chrome](https://github.com/hexated/cloudstream-extensions-hexated/assets/155451775/3d252497-23df-469e-a007-66dda6a268c6)
When play in browser its showing for both chamnel working snd not working

**Comment by subby2006** [comment]
> @hexated
> 
> ![Screenshot_20240107-201739_Chrome](https://private-user-images.githubusercontent.com/155451775/294765814-3d252497-23df-469e-a007-66dda6a268c6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NjUyOTMsIm5iZiI6MTcwNDY2NDk5MywicGF0aCI6Ii8xNTU0NTE3NzUvMjk0NzY1ODE0LTNkMjUyNDk3LTIzZGYtNDY5ZS1hMDA3LTY2ZGRhNmEyNjhjNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QyMjAzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmRlMGU5YmM5ODkzZWZjODgxZGQ1ZTkxNmZlOGE4Yjk0ODhmOWVjMGIyYWRhMzZjMGJiNWI2OGI2YzI4ODczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vbRybABpaoYxztSMLVMlN6TfGYSSYot1sxl_OXhApts) When i choose play in browser in cs its showing for both channels which are working and not working .. idk if it helps

You will get blocked message if you try to open link directly on browser, m3u8 requires referrer to open

**Comment by heliosII** [comment]
> > @hexated
> > ![Screenshot_20240107-201739_Chrome](https://private-user-images.githubusercontent.com/155451775/294765814-3d252497-23df-469e-a007-66dda6a268c6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NjUyOTMsIm5iZiI6MTcwNDY2NDk5MywicGF0aCI6Ii8xNTU0NTE3NzUvMjk0NzY1ODE0LTNkMjUyNDk3LTIzZGYtNDY5ZS1hMDA3LTY2ZGRhNmEyNjhjNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QyMjAzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNmRlMGU5YmM5ODkzZWZjODgxZGQ1ZTkxNmZlOGE4Yjk0ODhmOWVjMGIyYWRhMzZjMGJiNWI2OGI2YzI4ODczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vbRybABpaoYxztSMLVMlN6TfGYSSYot1sxl_OXhApts) When i choose play in browser in cs its showing for both channels which are working and not working .. idk if it helps
> 
> You will get blocked message if you try to open link directly on browser, m3u8 requires referrer to open

I got you but my issue is still there when i play in cs

**Comment by subby2006** [comment]
hmm seems like they might’ve changed referrer requirements, Cabernet plug-in and the the daddylive addon in the crew repo updated recently

**Comment by heliosII** [comment]
@hexated now no channels working.. totally time4tv got error
