### ISSUE TITLE
Kinoger not working

### ISSUE THREAD

**Issue by Jerico3241** [hexated/cloudstream-extensions-hexated#505]
Hello the recent kinoger addon is not working no video is being played.

**Comment by hexated** [comment]
Works fine for me, use pre..
![Screenshot_20240107-214659.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/3ac1f690-7e4e-40ec-8f67-528861b793a1)

**Comment by Jerico3241** [comment]
I have now another issue sry for getting on your nerves but the title images are not in the right position they are always left or how should I say if you have Napoleon it has the image right from it like Godzilla
