### ISSUE TITLE
GoogleDriveIndex

### ISSUE THREAD

**Issue by phisher98** [hexated/cloudstream-extensions-hexated#506]
can we create a extension like this we can provide index and also Username and password to access that index which is hosted on GoogleDrive like Aniyomi created ?

https://github.com/aniyomiorg/aniyomi-extensions/blob/master/src/all/googledriveindex/src/eu/kanade/tachiyomi/animeextension/all/googledriveindex/GoogleDriveIndex.kt

**Comment by hexated** [comment]
Too lazy 🫠. Just use that in cloudstream. It should work with compat

**Comment by phisher98** [comment]
Hahaha No Problem Aniyomi Extension is not working but no issue i was just asking
