### ISSUE TITLE
Very good Movie site Dubbed showflix.space

### ISSUE THREAD

**Issue by phisher98** [hexated/cloudstream-extensions-hexated#510]
https://showflix.space 

Kindly add this website it has many good movies and series in Hindi

Likedev made it but its domain is not updated can you add it in this Repo 

https://github.com/LikDev-256/likdev256-tamil-providers/tree/master/ShowFlixProvider

**Comment by heliosII** [comment]
> https://showflix.space
> 
> Kindly add this website it has many good movies and series in Hindi
> 
> Likedev made it but its domain is not updated can you add it in this Repo
> 
> https://github.com/LikDev-256/likdev256-tamil-providers/tree/master/ShowFlixProvider

Adding this as seperate provider is good or adding like vega i.e. one 4k quality link then one 1080p link(with highest size for 1080p)

**Comment by SaurabhKaperwan** [comment]
> https://showflix.space 
> 
> Kindly add this website it has many good movies and series in Hindi
> 
> Likedev made it but its domain is not updated can you add it in this Repo 
> 
> https://github.com/LikDev-256/likdev256-tamil-providers/tree/master/ShowFlixProvider

It is already present in sorastream

**Comment by heliosII** [comment]
> > https://showflix.space
> > Kindly add this website it has many good movies and series in Hindi
> > Likedev made it but its domain is not updated can you add it in this Repo
> > https://github.com/LikDev-256/likdev256-tamil-providers/tree/master/ShowFlixProvider
> 
> It is already present in sorastream

Source name??

**Comment by SaurabhKaperwan** [comment]
> > It is already present in sorastream
> 
> Source name??

Streamwish and streamruby

**Comment by phisher98** [comment]
Its from this website ?

**Comment by SaurabhKaperwan** [comment]
> Its from this website ?

Yes

**Comment by heliosII** [comment]
>
> Streamwish and streamruby

Streamruby has a problem as it is showflix.. it should have multi audio i.e. loki is available in hindi and english and other language but it dont show multiple tracks(only english play)and i was watching a series in streamruby in which first 3 episode in hindi and then 4th episode in kannada(other language)

**Comment by phisher98** [comment]
Yes and I am unable to find any code related to source on github

**Comment by SaurabhKaperwan** [comment]
> >
> > Streamwish and streamruby
> 
> Streamruby has a problem as it is showflix.. it should have multi audio i.e. loki is available in hindi and english and other language but it dont show multiple tracks(only english play)and i was watching a series in streamruby in which first 3 episode in hindi and then 4th episode in kannada(other language)

Choose streamruby which have no quality next to it

**Comment by SaurabhKaperwan** [comment]
For hindi movies you can try SFMovies, Vcloud , gofile and multimovies in sorastream

**Comment by heliosII** [comment]
> 
> Choose streamruby which have no quality next to it
 
I got it now .. so there is no quality difference between streamruby 1080p and streamruby(then selection 1080p)

**Comment by SaurabhKaperwan** [comment]
> > 
> > Choose streamruby which have no quality next to it
>  
> I got it now ..thank you brother .. so there is no quality difference between streamruby 1080p and streamruby(then selection 1080p)
> 
> 

Well I don't see any difference.

**Comment by heliosII** [comment]
> 
> Well I don't see any difference.
Thank you brother for telling about streamruby ..

**Comment by phisher98** [comment]
Yeah and 800 one also as it's 1080 but showing 1920x800

**Comment by heliosII** [comment]
> Yeah and 800 one also as it's 1080 but showing 1920x800

Ik that thats mostly movies now are 1920×800 for ott

**Comment by SaurabhKaperwan** [comment]
> Yeah and 800 one also as it's 1080 but showing 1920x800 

19-20 video quality me hota rehta hai.

**Comment by heliosII** [comment]
> > Yeah and 800 one also as it's 1080 but showing 1920x800
> 
> 19-20 video quality me hota rehta hai.

Brother not seeing 1080p quality for streamruby in latest uploaded tv series like echo and killer soup(1080p avail on site).. can you please if the problem also on your side

**Comment by SaurabhKaperwan** [comment]
> > > Yeah and 800 one also as it's 1080 but showing 1920x800
> > 
> > 19-20 video quality me hota rehta hai.
> 
> Brother not seeing 1080p quality for streamruby in latest uploaded tv series like echo and killer soup(1080p avail on site).. can you please tell if the problem also on your side

Bro I just finished killer soup first episode

**Comment by SaurabhKaperwan** [comment]
> > For me it is not showing 1080p links for streamruby
> 
> Yes brother for movie and series no 1080p links showing from today.. maybe opening a issue will solve it

This problem is not related to sorastream it is because the website has not uploaded this movie in 1080p

**Comment by heliosII** [comment]
No they uploaded the tiger 3 movie in 1080p and till yesterday every streamruby showing 1080p now none of them mostly.. echo is also uploaded in 1080 on showflix check there @SaurabhKaperwan

**Comment by SaurabhKaperwan** [comment]
> echo is also uploaded in 1080 on showflix check there @SaurabhKaperwan 

![Screenshot_2024-01-11-18-30-50-70_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/hexated/cloudstream-extensions-hexated/assets/91174352/54e1edac-22e5-43fd-8530-3105aad0690a)

For 1080p in the website it is showing this. It is working for low quality.

**Comment by heliosII** [comment]
> 
> For 1080p in the website it is showing this. It is working for low quality.

No no .. killer soup is still uploading on server of showflix ... check "echo" it has 1080p but not on sors

**Comment by heliosII** [comment]
> They uploaded it but it is some server issue they can't handle that much load and for tiger 3 it is showing 1080p links in cloudstream.

Last latest (2 series) uploads not showing in 1080p..killer soup episode 2 is also opening in 1080p on showflix.. you can check that
