### ISSUE TITLE
Movierulzhd

### ISSUE THREAD

**Issue by safdar9633** [hexated/cloudstream-extensions-hexated#513]
Movierulzhd is not working.. please fix <3

**Comment by hexated** [comment]
Works fine for me, use pre, change DNS or try VPN
![Screenshot_20240111-201502.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/0bd75b3e-3e14-4923-939c-0e9ec4d954a9)

**Comment by safdar9633** [comment]
currently using this from UAE. It says no link found. The movierulz hd loads fine. Even from the globe icon the site loads fine.

**Comment by phisher98** [comment]
@safdar9633 try settings > general > DNS over HTTPS or use a VPN
