### ISSUE TITLE
Streamruby 1080p link missing

### ISSUE THREAD

**Issue by heliosII** [hexated/cloudstream-extensions-hexated#514]
the streamruby is not taking the 1080p quality in some of the content .  only showing till 720p. whereas those were in 1080p in showflix.
Ex. Echo is 1080p in streamflix but in sora showing only till 720p

**Comment by phisher98** [comment]
Which one Echo ? Link for it

**Comment by hexated** [comment]
scam, their hls only up to 720p => https://streamruby.com/e/ktk09r0ubyqj.html

```
#EXTM3U

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="English",LANGUAGE="en",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_l/index-a1.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="हिन्दी",LANGUAGE="hi",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_l/index-a2.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="తెలుగు",LANGUAGE="te",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_l/index-a3.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="தமிழ்",LANGUAGE="ta",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_l/index-a4.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1"

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=311086,RESOLUTION=640x360,FRAME-RATE=24.000,CODECS="avc1.64001e,mp4a.40.2",VIDEO-RANGE=SDR,AUDIO="audio0"
https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_l/index-v1-a1.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=471849,RESOLUTION=852x480,FRAME-RATE=24.000,CODECS="avc1.64001e,mp4a.40.2",VIDEO-RANGE=SDR,AUDIO="audio0"
https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_n/index-v1-a1.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=865015,RESOLUTION=1280x720,FRAME-RATE=24.000,CODECS="avc1.640020,mp4a.40.2",VIDEO-RANGE=SDR,AUDIO="audio0"
https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_h/index-v1-a1.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=19772,RESOLUTION=640x360,CODECS="avc1.64001e",URI="https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_l/iframes-v1-a1.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1",VIDEO-RANGE=SDR
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=32149,RESOLUTION=852x480,CODECS="avc1.64001e",URI="https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_n/iframes-v1-a1.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1",VIDEO-RANGE=SDR
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=59719,RESOLUTION=1280x720,CODECS="avc1.640020",URI="https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_h/iframes-v1-a1.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1",VIDEO-RANGE=SDR
```

**Comment by heliosII** [comment]
> scam, their hls only up to 720p => https://streamruby.com/e/ktk09r0ubyqj.html
> 
> ```
> #EXTM3U
> 
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="English",LANGUAGE="en",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_l/index-a1.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1"
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="हिन्दी",LANGUAGE="hi",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_l/index-a2.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1"
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="తెలుగు",LANGUAGE="te",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_l/index-a3.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1"
> #EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio0",NAME="தமிழ்",LANGUAGE="ta",AUTOSELECT=NO,DEFAULT=NO,CHANNELS="2",URI="https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_l/index-a4.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1"
> 
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=311086,RESOLUTION=640x360,FRAME-RATE=24.000,CODECS="avc1.64001e,mp4a.40.2",VIDEO-RANGE=SDR,AUDIO="audio0"
> https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_l/index-v1-a1.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=471849,RESOLUTION=852x480,FRAME-RATE=24.000,CODECS="avc1.64001e,mp4a.40.2",VIDEO-RANGE=SDR,AUDIO="audio0"
> https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_n/index-v1-a1.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=865015,RESOLUTION=1280x720,FRAME-RATE=24.000,CODECS="avc1.640020,mp4a.40.2",VIDEO-RANGE=SDR,AUDIO="audio0"
> https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_h/index-v1-a1.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1
> 
> #EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=19772,RESOLUTION=640x360,CODECS="avc1.64001e",URI="https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_l/iframes-v1-a1.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1",VIDEO-RANGE=SDR
> #EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=32149,RESOLUTION=852x480,CODECS="avc1.64001e",URI="https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_n/iframes-v1-a1.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1",VIDEO-RANGE=SDR
> #EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=59719,RESOLUTION=1280x720,CODECS="avc1.640020",URI="https://3uho6lzsf1c2o3i8oun9.streamruby.net/hls2/04/00060/ktk09r0ubyqj_h/iframes-v1-a1.m3u8?t=qetrfbtaXwK8hObLmW93a4biRqWYpeFthQ-8f8xNfoY&s=1705042095&e=43200&f=303573&srv=127.0.0.1",VIDEO-RANGE=SDR
> ```

Oo thats why it is not showing.. okay thanks for telling...waiting for the time4tv fix
