### ISSUE TITLE
Kinoger Download doesn't work 

### ISSUE THREAD

**Issue by Variant1987** [hexated/cloudstream-extensions-hexated#518]
When I try to download a movie or series via kinoger it works, but when I try to play it I always get: ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED (3003) Source Error. The file is also only 22kb in size.

**Comment by hexated** [comment]
Which one doesnt work, download or stream?
Also streaming works fine here
![Screenshot_20240107-214659.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/ce75a1cd-a31a-4f7d-ae62-2c8e056b9fef)

**Comment by Variant1987** [comment]
Streaming works fine. Try downloading for example "Game of Thrones (2014)"

**Comment by hexated** [comment]
Yeah, issue with app. Open there

**Comment by Variant1987** [comment]
But it does not work for every series, like the example I sent you before

**Comment by hexated** [comment]
![Screenshot_20240114-204330.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/f8b82537-1a2d-4759-ad96-8becb41c9a59)

**Comment by Variant1987** [comment]
As you can see in your screenshot, it downloads with 0 mbits. The video does not work even when it has finished downloading

**Comment by hexated** [comment]
Issue with app

**Comment by fire-light42** [comment]
> Hello, it working

Sounds like anti scrape, the downloader might have different params than the videoplayer causing video to work, but not download
