### ISSUE TITLE
Madsteam Live TV Tataplay

### ISSUE THREAD

**Issue by phisher98** [hexated/cloudstream-extensions-hexated#525]
https://madstream.one

https://madplay.live/hls/tata/

Dash

It is using jwplayer

Kindly add this it has live tv channels

**Comment by phisher98** [comment]
jwplayer("jwplayerDiv").setup({ 'preload': "auto", 'stretching': "exactfit", 'width': "100%", 'height': "200", 'image': "http://imagestataplay.whatsonindia.com/dasimages/landscape/1280x720/7D7A5EBCA3D492DAA16454B6122030E5DC27EE4F5.jpg", 'logo': "http://imagestataplay.whatsonindia.com/dasimages/landscape/1280x720/7D7A5EBCA3D492DAA16454B6122030E5DC27EE4F5.jpg", file: "https://bpprod7linear.akamaized.net/bpk-tv/irdeto_com_Channel_307/output/manifest.mpd", type: "dash", drm: { "clearkey": { "keyId":"db6f1dbe0c005c2694914cca4791f6d5","key":"6f78f46833022785c8df240e5a13d94a" } }
});

**Comment by heliosII** [comment]
Madstream site is down and app also.. now they launched a app rogstream .. which is working 100% ..

**Comment by phisher98** [comment]
![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/153359846/4f96be4d-554e-4414-9db1-395bc2a638d5)
Working

**Comment by heliosII** [comment]
> Working

Yeah kinda only tataplay .. but previously it has voot,sonyliv,jiotv,samsungtv+,zee5,discovery+,epic on.. which is now on the new app only

**Comment by phisher98** [comment]
I don't trust any app other than CS

**Comment by heliosII** [comment]
> I don't trust any app other than CS

Yaa its also only uploaded on their tg... so kinda more sus...

**Comment by Mrunknow3** [comment]
New website of madstream
https://madstream.one/

**Comment by phisher98** [comment]
https://madplay.live/hls/tata/

new

**Comment by phisher98** [comment]
hi @hexated I have done all other work just stuck on unpacking the script contains file link,key and keyid type dash so if you can help me with that to load link and play it using https://recloudstream.github.io/dokka/-cloudstream/com.lagradost.cloudstream3.utils/-drm-extractor-link/index.html?query=open%20class%20DrmExtractorLink%20:%20ExtractorLink
maybe we can chat on discord as well
