### ISSUE TITLE
Add aniwatch in anichi

### ISSUE THREAD

**Issue by SaurabhKaperwan** [hexated/cloudstream-extensions-hexated#526]

**Comment by phisher98** [comment]
aniwatch in anichi ?

**Comment by SaurabhKaperwan** [comment]
> aniwatch in anichi ?

Anichi scrap from multiple websites like gogo and crunchyroll

**Comment by hexated** [comment]
Anchi doesnt work like Sora. Its their own app the one who scrape from multiple website. I only scrape their app
