### ISSUE TITLE
Time4tv total error

### ISSUE THREAD

**Issue by heliosII** [hexated/cloudstream-extensions-hexated#528]
All the sites now showing error nothing working
![Screenshot_20240114-222528_CloudStream Beta](https://github.com/hexated/cloudstream-extensions-hexated/assets/155451775/eb7e609c-a9c9-4148-b20e-e44268d4eae3)

**Comment by heliosII** [comment]
Now everything working ... but i am letting the issue open.. if the problem come again.. its scrapping or making m3u problem i think

**Comment by khateeb1970** [comment]
Not working for me
