### ISSUE TITLE
Movierulzhd catalog seems empty

### ISSUE THREAD

**Issue by MixSens** [hexated/cloudstream-extensions-hexated#535]
Movierulzhd catalog seems empty while opening the app

**Comment by ShankarKSH001** [comment]
Because that site's domain changed to https://movierulzhd.dog/

**Comment by Mrunknow3** [comment]
Just go setting<General<Clone site<find movierulzhd and click<name whenever you want <example.com paste this https://movierulzhd.dog/<Language type Hi < ok now work it![Screenshot_2024-01-17-17-46-20-693_com.lagradost.cloudstream3.prerelease.jpg](https://github.com/hexated/cloudstream-extensions-hexated/assets/154901963/ef90937c-04b5-4efe-820c-14c77d39bda7)
