### ISSUE TITLE
Animesaga no links still

### ISSUE THREAD

**Issue by phisher98** [hexated/cloudstream-extensions-hexated#536]
So i have checked its source its showing 
![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/153359846/f4984d84-73fb-46c5-97e1-05c6057c5728)

**Comment by hexated** [comment]
> So i have checked its source its showing 
> ![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/153359846/f4984d84-73fb-46c5-97e1-05c6057c5728)
> 

Works fine for me, make sure using pre.
Change DNS or try VPN

**Comment by HaxerAhmed** [comment]
I tried with vpn and without vpn but its not showing on my poco x2
