### ISSUE TITLE
help

### ISSUE THREAD

**Issue by darkwaters-coder** [hexated/cloudstream-extensions-hexated#538]
how do i add this repo since i looked on this site 'https://rentry.org/cs3-repos' and they have not updated the repos is there any other source help me with plzzzz

**Comment by hexated** [comment]
Type "megarepo" in Repository URL
It'll install all repo

**Comment by darkwaters-coder** [comment]
but my hexated provider does not have superstream

**Comment by hexated** [comment]
> but my hexated provider does not have superstream 
> 

Thats weird. Try this https://pastebin.com/raw/wCLbicz9
