### ISSUE TITLE
Superstream

### ISSUE THREAD

**Issue by Abodabodd** [hexated/cloudstream-extensions-hexated#540]
Some series and movies not work like Jujutsu kaisen s2 ep 1 and it load 1 link 
But still very good work and better than superstream from anyomi
Thnx ❤️❤️

**Comment by phisher98** [comment]
Use Aniwave,Aniwatch for Anime content better than using sora or superstream

**Comment by Abodabodd** [comment]
> Use Aniwave,Aniwatch for Anime content better than using sora or superstream

I use Jujutsu for example and there's alot of movie load just 1080 link and that not good for who have slow internet

**Comment by Abodabodd** [comment]
> Aniwave slow? you must be live in cave. Also there are anichi or last option gogo

I didn't say aniwave is slow and i not even talking about anime i just use Jujutsu as example
And what i say is A lot of movie (not anime) are show link just of 1080 and some people who have slow internet can't watch it without lagging

**Comment by heliosII** [comment]
> I didn't say aniwave is slow and i not even talking about anime i just use Jujutsu as example And what i say is A lot of movie (not anime) are show link just of 1080 and some people who have slow internet can't watch it without lagging

 then use 720p in sora or hdmovie2

**Comment by Abodabodd** [comment]
> > I didn't say aniwave is slow and i not even talking about anime i just use Jujutsu as example And what i say is A lot of movie (not anime) are show link just of 1080 and some people who have slow internet can't watch it without lagging
> 
> then use 720p in sora or hdmovie2 or superstream if available

The name of my problem is (superstream) that's
Mean i talk about superstream not another extension
And i already use sora and the other site but superstream is better in subtitles
Its better than the anime extension (in arabic)

**Comment by heliosII** [comment]
> The name of my problem is (superstream) that's Mean i talk about superstream not another extension And i already use sora and the other site but superstream is better in subtitles Its better than the anime extension (in arabic)

Haha.. we cant do magic to increase your speed.. a specific movie of specific time and size will need a minimum amount of speed to play without buffer... if there is no 720 avail in so cant do anything

**Comment by Abodabodd** [comment]
> > The name of my problem is (superstream) that's Mean i talk about superstream not another extension And i already use sora and the other site but superstream is better in subtitles Its better than the anime extension (in arabic)
> 
> Haha.. we cant do magic to increase your speed.. a specific movie of specific time and size will need a minimum amount of speed to play without buffer... if there is no 720p avail in so cant do anything

My internet are good Why don't you focus on the problem? You always go in another direction. It's like I ask to fix SoraStream and I say it's broken. I tried to play Naruto episodes and the app stopped and it says someone used Aniyomi. The problem is with Superstream and not with another add-on and it's not with my internet. I already know what works.  And what doesn't work.  the whol point is I hope to modify it to bring the complete list of links if it could be

**Comment by Abodabodd** [comment]
> For me its working fine.. so dont know that its broken or have error

Its very good that why i need to use another one + try to play Jujutsu kaisen s2 ep 1 or 2 or try solo leveling(ore dake level up) ep2 and you will understand what I meaning

**Comment by hexated** [comment]
They only provide 360p and hls link. The one you ask need account. I can add 360p if you want

**Comment by Abodabodd** [comment]
> They only provide 360p and hls link. The one you ask need account. I can add 360p if you want

That's what I mean👇
https://cdn.discordapp.com/attachments/1145016253317136394/1198196231126646845/Screenrecorder-2024-01-20-12-22-09-760.mp4?ex=65be0632&is=65ab9132&hm=501eafdeced9d63ee920200ab7c412e71c06a8ea7ffe38731b704c43313662c8&
You can see the 1080 link are not loading I think it's because it's damaged The superstream add-on works and brings links, but mostly only one link from each  api and mostly 1080p. So sometimes, if the link works, the movie works, like the movie Lift 2024, it works, but links like Jujutsu Kaisen S2 Ep1 do not work because the link itself is damaged in the febbox, so I am not an expert in these matters.  But if you are able to make it fetch all the movie links from the api then I will be grateful

 Even if it requires an account, you can add a place to put the account in the extension settings, such as time 4tv, if you can do it, please. Also, I do not use 360p resolution, but perhaps someone will benefit from it.

**Comment by hexated** [comment]
Is that mbp? Also since when time4tv required account

**Comment by Abodabodd** [comment]
> Is that mbp? Also since when time4tv required account

Its my fault i men maci iptv  in french repo
And watch the video that I send it to understand what i mean

**Comment by Abodabodd** [comment]
> Is that mbp? Also since when time4tv required account

And fstream also use account options

**Comment by hexated** [comment]
How much storage febbox give?

**Comment by Abodabodd** [comment]
> How much storage febbox give?

I don't know i don't have vip
And i think its have unlimited download

**Comment by hexated** [comment]
Its will save to your storage right? After that you can download

**Comment by Abodabodd** [comment]
> Its will save to your storage first, right? After that you can download

/storage/emulated/0/Download/febbox
Or any folder you choose it 
I choose this and i use it to download free by any quality i need from febbox but its download without subtitles and i need to watch direct its better than download

**Comment by hexated** [comment]
How you share your file from mbp to febbox?

**Comment by Abodabodd** [comment]
> How do you export file from mbp to febbox?

Hhh i think mbp mean megabytes
I use showbox watch this video

https://cdn.discordapp.com/attachments/1145016253317136394/1198245537493831790/Screenrecorder-2024-01-20-15-38-31-900.mp4?ex=65be341e&is=65abbf1e&hm=b570febee652bbd93ecad853fc16879e169ccff3ba784e56d9e292db12dbc013&

That's the button you need to click on it👇

https://cdn.discordapp.com/attachments/1145016253317136394/1198245711762964510/Screenshot_------_com.tdo.showbox-edit.jpg?ex=65be3448&is=65abbf48&hm=c2843d1ae6d15f727746744f2f418a27e512f49157c8c5d298f1b8ef0f13b47f&

**Comment by hexated** [comment]
Ill delete all this message, don't want them notice

**Comment by hexated** [comment]
#549
