### ISSUE TITLE
Site Req.: Movi & Animerulz

### ISSUE THREAD

**Issue by krishus96** [hexated/cloudstream-extensions-hexated#543]
1. Website Link: https://www.movi.pk/
Language: hi
Description: 1080p Content with multi-audio available.

2. Link: https://animerulz.in/
Language: hi.
Description: 1080p Content available with Hindi Audio

**Comment by hexated** [comment]
India everyday 😑😑.

Movipk uses same source with allmovieland & animerulz clone with  #524

**Comment by Mrunknow3** [comment]
Most population country is india in world with 1.43 billion.
