### ISSUE TITLE
Movierulzhd catalogue  seems empty

### ISSUE THREAD

**Issue by abbae07** [hexated/cloudstream-extensions-hexated#544]
4 days back had changed to new domain
https://movierulzhd.dog/
but today the current domain is showing error
How to fix this domain..?is there a new one..?

**Comment by IndusAryan** [comment]
they changed today again to .party , and instead of issues, just clone it with clone setting everytime just by searching movierulz

**Comment by abbae07** [comment]
just asking out of context..how do you do the same for bolly2tolly..what's the working domain and language code..?

**Comment by IndusAryan** [comment]
is b2t even present in hexated or any other repo, to find new domains search for site and go to site itself, most of the case the old url redirects to new url

**Comment by abbae07** [comment]
It is there in Likdev, I  tried to clone it similarly to movierulz but didn't work

**Comment by IndusAryan** [comment]
means the plugin is broken more than just url
