### ISSUE TITLE
HOW Sorastream Work?

### ISSUE THREAD

**Issue by Mrunknow3** [hexated/cloudstream-extensions-hexated#545]
Smovies not showing

**Comment by SaurabhKaperwan** [comment]
> Smovies not showing

It scraps from multiple websites

**Comment by Mrunknow3** [comment]
What about smovie have multiple languages but it's not showing.it's sorastream scrap

**Comment by SaurabhKaperwan** [comment]
> What about smovie have multiple languages but it's not showing.it's sorastream scrap

SFMOVIES removed all movies and now they only have 10 movies.

**Comment by Mrunknow3** [comment]
Add another good source who have multiple languages.
