### ISSUE TITLE
Maintainance/update required for sites: AnimeDekho

### ISSUE THREAD

**Issue by dewxo** [hexated/cloudstream-extensions-hexated#553]
AnimeDekho:
Partially working, catalogue is loaded but some streams works some do not;

Tested with VPNs too (Manchester/WDC)

**Comment by ShankarKSH001** [comment]
You need to skip ad in the site for every 24 hours.

**Comment by dewxo** [comment]
This issue is solved!, I must close this issue, Thanks!💕

**Comment by HaxerAhmed** [comment]
Not solved its still showing watch ad for 24h 1times

**Comment by devvratmiglani** [comment]
You need to refresh the page, the problem was some streams were not working that is fix now!
