### ISSUE TITLE
Miniopai (id) no link found

### ISSUE THREAD

**Issue by WEPOXS** [hexated/cloudstream-extensions-hexated#556]
![Screenshot_20240127_151159_CloudStream.jpg](https://github.com/hexated/cloudstream-extensions-hexated/assets/146017577/0e4c9706-6d25-4f0e-9493-2a00a9db99a5)

No Links Found 
Source error
ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED (3003)
 Source error

**Comment by hexated** [comment]
Should work now
