### ISSUE TITLE
 Issue Time4tv 

### ISSUE THREAD

**Issue by owencz1998** [hexated/cloudstream-extensions-hexated#56]
Some links won't play like Liverpool tv on the website it works but not on the app

**Comment by owencz1998** [comment]
Also I was watching sky sports main stream and all the sudden I'm getting bad https error and now will not work

**Comment by hexated** [comment]
> Some links won't play like Liverpool tv on the website it works but not on the app

Any other channel like that?

**Comment by owencz1998** [comment]
All channels don't work no more nothing at all dude literally started to watch something and then it's cut off completely dude

**Comment by hexated** [comment]
> All channels don't work no more nothing at all dude literally started to watch something and then it's cut off completely dude 

They added drm, the end of era

**Comment by owencz1998** [comment]
Does that mean they have stopped for good as the website is still letting me watch stuff dude

**Comment by owencz1998** [comment]
Ahh they fixed it mate haha 😄
