### ISSUE TITLE
Update docs to include instructions to create new plugins.

### ISSUE THREAD

**Issue by h2210316651** [hexated/cloudstream-extensions-hexated#561]
The docs have no instructions on how to create a new plugin. This would help new developers onboard to committing to this repo.

**Comment by IndusAryan** [comment]
https://recloudstream.github.io/csdocs/

**Comment by h2210316651** [comment]
> https://recloudstream.github.io/csdocs/

Hey thanks for the docs, will you be willing to merge PRs if I can make new providers??

**Comment by IndusAryan** [comment]
no you can PR, they will merge automatically after some time. i am not owner of this repo
