### ISSUE TITLE
Can you plesae tell on which codec does anime dekho and anime saga videos play on ?

### ISSUE THREAD

**Issue by Mileymehak** [hexated/cloudstream-extensions-hexated#562]
Okay so something funny happened. Anime dekho and anime saga videos play on my samsung phone as well as on my Sony android tv but they show error in playing on my mi android box, but other sources have no problem in playing. Is there something to do with the codec of these videos or maybe the video format that is specifically not played by my android box ?
I know it's a minor thing but can you look into it and let me know if I can do something about it ?
Thank you. 🫰🏻
P.S. just did a few experiments. These videos do not play in either vlc, mpv, web browser or web cast player, as they keep saying I do not have permission. It's just internal player that plays them on my phone as well.

**Comment by hexated** [comment]
About codex, i cant do it from extension.
And animesaga only work in internal player due to header and cant fix it
