### ISSUE TITLE
Add Moviefiction

### ISSUE THREAD

**Issue by Mrunknow3** [hexated/cloudstream-extensions-hexated#563]
https://moviefiction.com/

**Comment by phisher98** [comment]
@Mrunknow3  Bro this website have 10 or something movies only not a good source to be added

**Comment by Mrunknow3** [comment]
Oke vro but fix v-cloud in sorastresm

**Comment by phisher98** [comment]
@Mrunknow3 issue already raised by someone https://github.com/hexated/cloudstream-extensions-hexated/issues/618

you can closr this one and track there

**Comment by Mrunknow3** [comment]
Oke fix soon I close it

**Comment by phisher98** [comment]
@Mrunknow3 Hex will take a look at that i don't m8 hahaha

**Comment by Mrunknow3** [comment]
Oke vro hahahaha

**Comment by Mrunknow3** [comment]
Wbu #525 vro
