### ISSUE TITLE
Vegamovie(v-cloud) add v-cloud in anime cartoon section too bcz v-cloud have almost all hindi cartoon and anime too. 
Sorastream has best extension if you do it it more good

### ISSUE THREAD

**Issue by Mrunknow3** [hexated/cloudstream-extensions-hexated#570]

**Comment by hexated** [comment]
Sora(Tmdb) is awfull when dealing with anime

**Comment by Mrunknow3** [comment]
I am not saying about tmdb just I say anime or animation me v-cloud nhi aata jbki v cloud ke pass multiple audio h. Aur abhi animedekho or animesaga bhi work nhi kar rhe
