### ISSUE TITLE
Anime dekho no link found problem

### ISSUE THREAD

**Issue by HaxerAhmed** [hexated/cloudstream-extensions-hexated#571]
Anime dekho no link found problem

**Comment by Ar324066** [comment]
Yes, Repository Named Anime Dekho link not found please fix this

**Comment by dewxo** [comment]
Yes, its not working again for some reason

**Comment by phisher98** [comment]
Try Animesaga still then

**Comment by dewxo** [comment]
AnimeSaga never worked for me, it has the same issue!

**Comment by Ar324066** [comment]
Anime Saga not working for me Either
