### ISSUE TITLE
Book app

### ISSUE THREAD

**Issue by Mrunknow3** [hexated/cloudstream-extensions-hexated#572]
You make novel app. You can make book app book like rich dad poor dad, all knowledge book not imagination. I don't find any good where you stream book. Pls make app Or add book extension in quicknovel. 

Humble request

**Comment by hexated** [comment]
Sorry, I don't work in quick novel

**Comment by Mrunknow3** [comment]
Oke

**Comment by Mrunknow3** [comment]
Quick novel development stop he not replying any issue.
