### ISSUE TITLE
Anime Dekho Repository Problem

### ISSUE THREAD

**Issue by Ar324066** [hexated/cloudstream-extensions-hexated#573]
When I add any show from this repository in Library and try to open it says ( some kind of error) like this 
![Screenshot_2024-02-02-19-56-00-300_com lagradost cloudstream3](https://github.com/hexated/cloudstream-extensions-hexated/assets/157940568/34b6c3e0-3071-4395-9e79-19915c6a056f)
I also tried it on other devices but it says the same thing

**Comment by hexated** [comment]
Can you open their site on browser?

**Comment by phisher98** [comment]
Working fine update the app to 4.3.1 Pre-release

**Comment by Ar324066** [comment]
I tried what you said but still not working

**Comment by phisher98** [comment]
![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/153359846/75c59252-7a38-4a01-a201-033eeb0d58e2)
Working fine try to clear cache or reinstall maybe

**Comment by dontseehereStopMotion** [comment]
Works for me, maybe site was temporarily down yesterday. Please check site is working first before creating issue

![WhatsApp Image 2024-02-03 at 19 38 53](https://github.com/hexated/cloudstream-extensions-hexated/assets/149931560/0e68ffc2-0de2-4db6-bd77-77ddd846d8f2)

**Comment by dontseehereStopMotion** [comment]
Wait it only shows the video links but none of them work, good that its Saturday today

**Comment by Ar324066** [comment]
Bor, When you search any show it works but if you add it in your library for example ( your watching library ) and you try to open the show from library then it shows the error try it and telle what happened .
It'll be helpful

**Comment by Ar324066** [comment]
> Works for me, maybe site was temporarily down yesterday. Edit: Looks like there was an actual issue with the site yesterday, sorry to bother, lord really removed the skip ads bs, amazzing
> 
> ![WhatsApp Image 2024-02-03 at 19 38 53](https://private-user-images.githubusercontent.com/149931560/302040784-0e68ffc2-0de2-4db6-bd77-77ddd846d8f2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5ODU2MjMsIm5iZiI6MTcwNjk4NTMyMywicGF0aCI6Ii8xNDk5MzE1NjAvMzAyMDQwNzg0LTBlNjhmZmMyLTBkZTItNGRiNi1iZDc3LTc3ZGRkODQ2ZDhmMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDNUMTgzNTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTllYmYzYzY4MGQ1YjEzYWIyM2RkNjRmNzM2MTdhM2U1NWY4NzEyMDcwMWQ5MWJmNWYzNmExNjU1ZGNiODJmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9aMbucbtp4FBVhOdOf1bSmzofTd1Ix045J5iEOFdO28)
Bor, When you search any show it works but if you add it in your library for example ( your watching library ) and you try to open the show from library then it shows the error try it and telle what happened .
It'll be helpful

**Comment by Ar324066** [comment]
Bor, When you search any show it works but if you add it in your library for example ( your watching library ) and you try to open the show from library then it shows the error try it and telle what happened .
It'll be helpful
