### ISSUE TITLE
Anime saga no link found

### ISSUE THREAD

**Issue by HaxerAhmed** [hexated/cloudstream-extensions-hexated#576]
I am using Xiaomi Poco X2. In my device and so many device its not working and i tried so many vpn but didn’t work. Can u do something why its happening? And thank u bro u did many things for us. Love u so much bro ❤️

**Comment by ShankarKSH001** [comment]
Use beta app bro

**Comment by phisher98** [comment]
![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/153359846/293c673e-ada1-4266-beca-4723ccf2087a)
Working fine

**Comment by HaxerAhmed** [comment]
Then why its not working in my device?

**Comment by HaxerAhmed** [comment]
> Use beta app bro

Used 4.0.0 version but still not working

**Comment by phisher98** [comment]
Latest version is 4.3.1 not 4.0.0 Update it to pre release version

**Comment by ShankarKSH001** [comment]
> > Use beta app bro
> 
> Used 4.0.0 version but still not working

https://github.com/recloudstream/cloudstream/releases/download/pre-release/app-prerelease-release.apk
Install this beta version

**Comment by HaxerAhmed** [comment]
Working in beta version tnx❤️
