### ISSUE TITLE
Superstream now says "No Links Found"

### ISSUE THREAD

**Issue by TheWrightStuff1994** [hexated/cloudstream-extensions-hexated#579]
Also it says that I'm blocked from there site what is up with that?
https://showbox.shegu.net/

**Comment by Mrunknow3** [comment]
Mine it's working fine in animyomi but not working on cloudstream.

**Comment by hexated** [comment]
> Mine it's working fine in animyomi but not working on cloudstream. 

Install it from my repo

**Comment by hexated** [comment]
> Also it says that I'm blocked from there site what is up with that?
> https://showbox.shegu.net/

It should working now
