### ISSUE TITLE
Animesaga not working 

### ISSUE THREAD

**Issue by ShankarKSH001** [hexated/cloudstream-extensions-hexated#581]
Animesaga not working. 
It shows "connection Timeout please try again later ".

**Comment by phisher98** [comment]
![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/153359846/f8038752-4115-45dd-a747-e48e4461e700)
Working fine try to change DNS to Cloudflare or something

**Comment by ShankarKSH001** [comment]
Yeah now it's working without changing dns thanks for reply.

**Comment by phisher98** [comment]
no problem buddy close this issue if resolved
