### ISSUE TITLE
add tracking feature in sora-stream

### ISSUE THREAD

**Issue by WEPOXS** [hexated/cloudstream-extensions-hexated#591]
![Screenshot_20240210_042424_CloudStream.jpg](https://github.com/hexated/cloudstream-extensions-hexated/assets/146017577/4bf85525-6a5a-4637-8ace-bf9b153cf321)
Sora-stream

![Screenshot_20240210_042244_CloudStream.jpg](https://github.com/hexated/cloudstream-extensions-hexated/assets/146017577/3461ee58-e79f-4344-9631-87b9b413a965)
Not sora-stream

**Comment by WEPOXS** [comment]
I don't know whether it's possible or not, I hope it's possible because for websites that like to change URL, it's very troublesome to have to re-add things like the number of views and tracking.

**Comment by hexated** [comment]
Not possible, and sora only support simkl tracking

**Comment by WEPOXS** [comment]
> Not possible, and sora only support simkl tracking

so are you going to add for anilist and mal tracking?
