### ISSUE TITLE
Have questions and suggestions 

### ISSUE THREAD

**Issue by Krishna-art-dev** [hexated/cloudstream-extensions-hexated#595]
• In Sora stream , allmovieland server name

• What is the use of stremiox extension,  cloud stream cannot play torrents and why would anyone just wants movie catalogue,
So there is another reason for it? I found that hanime works on stremio extension in cloudstream 😂

I saw that a person was asking scrap movie from xyz site 
If you can able to do it, then do it on allmovieland app which can be downloaded from allmovieland.fun website

App is not like website, I checked it 
It's like website limit search app doesn't
For example:- I searched kungfu panda on Website no results and says it this
![Screenshot_2024-02-13-04-09-48-74_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/hexated/cloudstream-extensions-hexated/assets/121063162/c1de169b-5f47-4ff5-a45f-5ccc7a4cba6c)

And in app it shows this 
![Screenshot_2024-02-13-04-11-09-50_be6fcdca90135e844aba4464a4b13992](https://github.com/hexated/cloudstream-extensions-hexated/assets/121063162/47a796aa-688c-49bf-aab9-d5427b0bc713)

There's a difference in servers or something else idk 

• Have a problem while using aniyomi extension from Anicompat repo in cloudstream, hanime streaming worked fine
But downloading hentai from that hanime
Extension isn't good, it got downloaded, took my net and storage but it shows error while playing any hentai 

Shows this error 
![IMG_20240213_020845](https://github.com/hexated/cloudstream-extensions-hexated/assets/121063162/d9fcc326-44fe-44f6-9030-f22567af6b6a)

Tried using aniwatch from aniyomi extension, it worked it hentai got downloaded and can be played without problems 

Tried dantotsu app to download it from that same hanime app but this time from dantotsu it worked and played without error

Why this is happening?

**Comment by Krishna-art-dev** [comment]
• Any download manager which download movie anime in big packet not in small packets

Meaning like downloading from 1dm is like it downloadeds small packets of movies again and again till whole movie download and it merged everything into one to be like proper movie 
Problem is that it heats my phone a lot 

So any other download manager which download it at once like it downloads in browser or default cloudstream download

**Comment by Mrunknow3** [comment]
++

**Comment by Mrunknow3** [comment]
Suggestions

 I think he can add iptv player in app bcz that male tv more smooth

Bug

V-cloud in sora stream I watch all movie and series in v-cloud bcz he have hindi audio but something 10-15 day that not showing in sorastream

Suggestion:

I can think he make different extension for v-cloud it batter.

**Comment by hexated** [comment]
I just stick with website, easy to scrape. and for aniyomi compat, open your issue in here : https://github.com/CranberrySoup/AniyomiCompatExtension
