### ISSUE TITLE
Turkish TV Series [Site Request]

### ISSUE THREAD

**Issue by bachig26** [hexated/cloudstream-extensions-hexated#6]
The below Providers are one of the sites which have most of the Turkish TV Series in English Subtitled, also in this sites the subs are fan subbed and hardcoded to video, so no separate Subtitle option.

_I'm providing here are two separate sites which have most of same contents, Turkish123 site is oldest and YoTurkish is newest one. so, I think you don't wanted add both sites, it would be great to have just the Turkish123._

**Turkish123: https://turkish123.com/** [https://turkish123.site, this is the info site for Turkish123 which has also the alternate domain incase of any ISP block and reference.]
**YoTurkish: https://www.yoturkish.com/**

also, they add the sometimes change in domain with like `https://www1.yoturkish.com/home/` and `https://turkish123.com/home-1/`, like this with `www1` and `/home-1 instead of just /home`.

I also think the servers are same for the both site, maybe you need to check it. also there are 4 servers.

also there are 3 download (Fembed) servers i think.

_ps. I know that this is my 3rd site request and if you don't want to do this many, it would great to add this request and WLEXT request, and reject MxDrama request as Turkish only sites providers are not available in anywhere._

**Comment by hexated** [comment]
Added Turkish123
