### ISSUE TITLE
Sorastream 🔗 superstream integration

### ISSUE THREAD

**Issue by M-BOUAB** [hexated/cloudstream-extensions-hexated#604]
Why is superstream now separated from sorastream? Sorastream has the best TMDB integration which makes the UI better, while superstream UI is not as good. But at the same time superstream has the best quality links. An integration between sorastream UI & superstream links seems to be a good idea (or maybe not, I'm not a dev)

**Comment by hexated** [comment]
> If superstream is good now and you think it will become excellent if it is merged with sorastream, then you are wrong.

💯
