### ISSUE TITLE
YouTube movies with ads

### ISSUE THREAD

**Issue by M-BOUAB** [hexated/cloudstream-extensions-hexated#611]
YouTube has a lot of movies that are free with ads, is it possible to add it to the list of websites you're scraping from?

**Comment by IndusAryan** [comment]
install Invidious extension from official cloudstream extension repository

**Comment by M-BOUAB** [comment]
I know about invidious, I didn't clarify my comment enough, I mean add it to sorastream, so that when a movie is already available for free on YouTube, why would someone bother streaming it from vidsrc, it'll be much better if we can see YouTube in the list of sources available for a specific movie in sorastream.
For example, the movie arrival is available on YouTube under the label "free with ads" in the movies section, so why not scrape it as a playable source in sorastream the same way Crunchyroll is scraped as a playable source in sorastream?
Maybe that's not possible though, because I don't think YouTube uses TMDB for its movies metadata

**Comment by hexated** [comment]
Yeah, not possible. TMDB -> YouTube 😑.
