### ISSUE TITLE
Doesn't Sora stream can able to play crunchyroll hindi dub anime?

### ISSUE THREAD

**Issue by Krishna-art-dev** [hexated/cloudstream-extensions-hexated#617]
Like kamyroll or yomiroll just asking because of curiosity

Already using Anicompat with yomiroll to watch hindi anime with highest quality 😅

**Comment by ShankarKSH001** [comment]
> Like kamyroll or yomiroll just asking because of curiosity
> 
> Already using Anicompat with yomiroll to watch hindi anime with highest quality 😅

Yomiroll is not working for me it shows only sub and dub & what is kamyroll

**Comment by Krishna-art-dev** [comment]
> > Like kamyroll or yomiroll just asking because of curiosity
> > Already using Anicompat with yomiroll to watch hindi anime with highest quality 😅
> 
> Yomiroll is not working for me it shows only sub and dub & what is kamyroll

In crunchyroll we can able to play English sub and English dub anime for free and kamyroll uses it's API to play crunchyroll animes on cloudstream
You can wonder why crunchyroll API if we have aniwave and other site, just because of its high quality and bitrate 

And yomiroll about yomiroll I will reply after checking it

**Comment by Krishna-art-dev** [comment]
> > > > Like kamyroll or yomiroll just asking because of curiosity
> > > > Already using Anicompat with yomiroll to watch hindi anime with highest quality 😅
> > > 
> > > 
> > > Yomiroll is not working for me it shows only sub and dub & what is kamyroll
> > 
> > 
> > In crunchyroll we can able to play English sub and English dub anime for free and kamyroll uses it's API to play crunchyroll animes on cloudstream You can wonder why crunchyroll API if we have aniwave and other site, just because of its high quality and bitrate
> > And yomiroll about yomiroll I will reply after checking it
> 
> I can't find kamyroll extension bro

You don't have to, it's down it's in avocado extension
Just use yomiroll from Anicompat and on its setting go to yomiroll setting and turn on local token then you can able to play Hindi animes

**Comment by Krishna-art-dev** [comment]
I have a question from you does your cloudstream updates your progress in anilist of any of the tracking site because mine don't
I have to track everything manually

**Comment by ShankarKSH001** [comment]
> > > > > Like kamyroll or yomiroll just asking because of curiosity
> > > > > Already using Anicompat with yomiroll to watch hindi anime with highest quality 😅
> > > > 
> > > > 
> > > > Yomiroll is not working for me it shows only sub and dub & what is kamyroll
> > > 
> > > 
> > > In crunchyroll we can able to play English sub and English dub anime for free and kamyroll uses it's API to play crunchyroll animes on cloudstream You can wonder why crunchyroll API if we have aniwave and other site, just because of its high quality and bitrate
> > > And yomiroll about yomiroll I will reply after checking it
> > 
> > 
> > I can't find kamyroll extension bro
> 
> You don't have to, it's down it's in avocado extension Just use yomiroll from Anicompat and on its setting go to yomiroll setting and turn on local token then you can able to play Hindi animes

![Screenshot_20240229-201953](https://github.com/hexated/cloudstream-extensions-hexated/assets/121159747/852fe6b2-0110-4491-9caf-dd8ed0ebef89)
I Can't go to settings

**Comment by ShankarKSH001** [comment]
> I have a question for you does your cloudstream updates your progress in anilist of any of the tracking site because mine don't I have to track everything manually

No bro I also update every list manually in library.
For anilist auto update i use dantotsu app

**Comment by Krishna-art-dev** [comment]
> > I have a question for you does your cloudstream updates your progress in anilist of any of the tracking site because mine don't I have to track everything manually
> 
> No bro I also update every list manually in library. For anilist auto update i use dantotsu app

But cloudstream was able to update it automatically, something is wrong have you report it 
Any extension recommendations for dantotsu

**Comment by ShankarKSH001** [comment]
> > > I have a question for you does your cloudstream updates your progress in anilist of any of the tracking site because mine don't I have to track everything manually
> > 
> > 
> > No bro I also update every list manually in library. For anilist auto update i use dantotsu app
> 
> But cloudstream was able to update it automatically, something is wrong have you report it Any extension recommendations for dantotsu

![Screenshot_20240229-212017](https://github.com/hexated/cloudstream-extensions-hexated/assets/121159747/a65d3be5-60a6-4704-b62b-681ed8770b5e)

**Comment by ShankarKSH001** [comment]
If you are new to that app first change dns to cloudflare in settings

**Comment by Krishna-art-dev** [comment]
> If you are new to this app first change dns to cloudflare in settings

No no I am thinking why your Anicompat isn't updated because of Isp blockage or anything
Your Anicompat is outdated

**Comment by Krishna-art-dev** [comment]
> Could you share how you installed aniyomi compat
![Uploading Screenshot_2024-02-29-21-27-59-39_cfa2fd239c8cded9285432912d0e0818.jpg…]()

**Comment by ShankarKSH001** [comment]
Can you share link for repos

**Comment by Krishna-art-dev** [comment]
> Can you share link for repos

Just type Anicompat in link and enter

**Comment by hexated** [comment]
> Like kamyroll or yomiroll just asking because of curiosity
> 
> Already using Anicompat with yomiroll to watch hindi anime with highest quality 😅

Yes, but i wont add it

**Comment by DESHRAJKUMAR** [comment]
> > > > > Like kamyroll or yomiroll just asking because of curiosity
> > > > > Already using Anicompat with yomiroll to watch hindi anime with highest quality 😅
> > > > 
> > > > 
> > > > Yomiroll is not working for me it shows only sub and dub & what is kamyroll
> > > 
> > > 
> > > In crunchyroll we can able to play English sub and English dub anime for free and kamyroll uses it's API to play crunchyroll animes on cloudstream You can wonder why crunchyroll API if we have aniwave and other site, just because of its high quality and bitrate
> > > And yomiroll about yomiroll I will reply after checking it
> > 
> > I can't find kamyroll extension bro
> 
> You don't have to, it's down it's in avocado extension
> Just use yomiroll from Anicompat and on its setting go to yomiroll setting and turn on local token then you can able to play Hindi animes

I failed to find Anicompat app

**Comment by Krishna-art-dev** [comment]
https://rentry.org/cs3-repos
