### ISSUE TITLE
Anichi fixes and features 

### ISSUE THREAD

**Issue by ITron-Legends** [hexated/cloudstream-extensions-hexated#622]
### stuff I guess 

- Use sorastream image and description parser thingy for episodes (current one is kinda unreliable and stops at like 40 episodes)
- Also use the sorastream trailer parser so we get English trailers. 
- Instead of listing the tv series length add the amount of sub/dub episodes 

*(The issue with the image and description parser is with one piece)*

**Comment by hexated** [comment]
Not possible, different meta
