### ISSUE TITLE
Superstream doesn't able to play Bollywood movies

### ISSUE THREAD

**Issue by Krishna-art-dev** [hexated/cloudstream-extensions-hexated#625]
It shows error while playing any Bollywood movies

**Comment by hexated** [comment]
Works fine for me,
![Screenshot_20240305-235942.png](https://github.com/hexated/cloudstream-extensions-hexated/assets/37908684/b807cb9f-4988-4302-a248-b0cbb1288fd9)

Make sure to use beta or change DNS

**Comment by Krishna-art-dev** [comment]
Not working for other Bollywood films

**Comment by Krishna-art-dev** [comment]
https://github.com/hexated/cloudstream-extensions-hexated/assets/121063162/7ffde2c3-9481-4eb8-9052-b10481eea32b

**Comment by Krishna-art-dev** [comment]
@hexated

**Comment by dewxo** [comment]
I should say partially working, some links work others do not

**Comment by Krishna-art-dev** [comment]
> I should say partially working, some links work others do not

Hmm idk but all anime and Hollywood movie works, I can tell from the much I check.

Idk about Bollywood just rrr works for me also not any other Bollywood movies

**Comment by phisher98** [comment]
Why don't you use Sorastream instead much better than Superstream
![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/153359846/076d3e89-3a1f-4702-9c39-4309b7f91742)

**Comment by Krishna-art-dev** [comment]
> Why don't you use Sorastream instead much better than Superstream ![image](https://private-user-images.githubusercontent.com/153359846/311416451-076d3e89-3a1f-4702-9c39-4309b7f91742.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NjQ4ODIsIm5iZiI6MTcwOTk2NDU4MiwicGF0aCI6Ii8xNTMzNTk4NDYvMzExNDE2NDUxLTA3NmQzZTg5LTNhMWYtNDcwMi05YzM5LTQzMDliN2Y5MTc0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwOVQwNjA5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGY1ZGQ5ODA0NDk5MTc3MmVlMTg2MDkyMDNiYTIyMDhmYjRkMDgxZTZiYWU2ZjFlOTQ3OWEyMjhiOTgwZWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5ygexruzQv31CL4HDoprZIA5sZ4EG5zBl3G56-SVVSw)

I use Sora stream but I found that Bollywood movies wasn't working so reported it

**Comment by Krishna-art-dev** [comment]
Hey do you know the use of stremio in cloudstream because cloud stream doesn't support torrent and stremio is a torrent application. Is there any use of stremiox or stremioc except using catalogue?
@phisher98

**Comment by phisher98** [comment]
Ok Buddy yeah maybe Superstream sources may don't contain the Movie thats why it shows no links but its shows poster as its extracting it from API like Sorastream

**Comment by phisher98** [comment]
@Krishna-art-dev Nope if you have Debian then only its good as it will download movie to debian and then stream it for you but i have tried with free once its not that efficient for free and debian is a paid service

**Comment by Krishna-art-dev** [comment]
> @Krishna-art-dev Nope if you have Debian then only its good as it will download movie to debian and then stream it for you but i have tried with free once its not that efficient for free and debian is a paid service

What is debian

**Comment by Krishna-art-dev** [comment]
@phisher98 hey I am new too this app
Do you have any repository and it's inside plugin (extension) recommendation for me 
I watch movies anime in hindi 
And on some issues of GitHub I found that Sora stream also have hindi sources
Can you tell me which are they I only know gofile v-cloud

**Comment by phisher98** [comment]
There are many Hindi Sources like Movie Movierulzhd,HDMovie2 and Sorastream also have many sources for Hindi content as well as try Likedev Repo it has Allmovieland Plugin as well if it works for you fine

**Comment by Krishna-art-dev** [comment]
> There are many Hindi Sources like Movie Movierulzhd,HDMovie2 and Sorastream also have many sources for Hindi content as well as try Likedev Repo it has Allmovieland Plugin as well if it works for you fine

Likdev-256 plugins never works sometimes before allmovieland and showflix worked but now they don't and most of his plugin didn't work for me 🥲
