### ISSUE TITLE
Dotmovies url changed

### ISSUE THREAD

**Issue by SaurabhKaperwan** [hexated/cloudstream-extensions-hexated#627]
Dotmovies is now rebranded as 
https://luxmovies.biz/

Please change the url.

**Comment by phisher98** [comment]
Nope https://dotmovies.one/ is working fine no change

**Comment by phisher98** [comment]
![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/153359846/6f2ac6cc-da78-4efa-b2cc-97b6dfa06243)

**Comment by SaurabhKaperwan** [comment]
It is a fake one. They are using Dotmovies name.

**Comment by SaurabhKaperwan** [comment]
Luxmovies and vegamovies have the same link of the telegram group but this Dotmovies have different telegram group link.

**Comment by SaurabhKaperwan** [comment]
And Dotmovies is not working in sorastream because they are using fake website.

**Comment by phisher98** [comment]
Then maybe hex can add this https://luxmovies.biz/ as one more source in Repo

**Comment by SaurabhKaperwan** [comment]
> Then maybe hex can add this https://luxmovies.biz/ as one more source in Repo

No only changing the url of Dotmovies will work.
