### ISSUE TITLE
Kickassanime.ro

### ISSUE THREAD

**Issue by venkat2305** [hexated/cloudstream-extensions-hexated#63]
Aniyomi added this site. Please add this site to the cloudstream. I've heard that encryption is messy but please refer to aniyomi extension and try to add this site. 8t has high quality anime

**Comment by venkat2305** [comment]
Bro, you are awesome 😎

**Comment by venkat2305** [comment]
@hexated unable to download from kickassanime. Please fix this

**Comment by hexated** [comment]
Internal download broken atm. Try external download like 1dm
