### ISSUE TITLE
Most of the sources available at fmoviesz and sflix are accesiible through sorastream. I tink vidcloud is avaialble in sorastream for example

### ISSUE THREAD

**Issue by erikk333** [hexated/cloudstream-extensions-hexated#639]
Most of the sources available at fmoviesz and sflix are accesiible through sorastream. I think filemoon is avaialble in sorastream for example
![afbeelding](https://user-images.githubusercontent.com/147526653/311776712-337274a3-42b9-4f07-8f46-b1547abd84e9.png)

**Comment by Mrunknow3** [comment]
What does it mean I do not understand sflix And fmovie have different sources but everything is accessible with cloudstream sorastresm. 

in this issue what you want
