### ISSUE TITLE
Sorastream bug

### ISSUE THREAD

**Issue by owencz1998** [hexated/cloudstream-extensions-hexated#64]
Issue when watching things it cuts me off sometimes and says remote error or something like that not sure if it's a app issue or sorastream

**Comment by hexated** [comment]
> Issue when watching things it cuts me off sometimes and says remote error or something like that not sure if it's a app issue or sorastream 

Send video, so i can check

**Comment by owencz1998** [comment]
I can later mate it just happens when I watch anything and it boots me off the program then comes up with remote error but once I'm home I'll send a video dude

**Comment by owencz1998** [comment]
https://user-images.githubusercontent.com/96526481/212417207-7efef169-d5e4-4f2b-90a4-d4191fbe4f7d.mp4

![Screenshot_20230113_205343_Gallery.jpg](https://user-images.githubusercontent.com/96526481/212417228-3409c17b-2625-4322-8457-15657b02e220.jpg)

**Comment by hexated** [comment]
> https://user-images.githubusercontent.com/96526481/212417207-7efef169-d5e4-4f2b-90a4-d4191fbe4f7d.mp4
> 
> ![Screenshot_20230113_205343_Gallery.jpg](https://user-images.githubusercontent.com/96526481/212417228-3409c17b-2625-4322-8457-15657b02e220.jpg)
> 
> 

Can you test with DNS of use VPN first?
Seems like network issue

**Comment by owencz1998** [comment]
Dns is adguard and it does it to most sources but seems to only happen at different times of the day hahaha 😆

**Comment by hexated** [comment]
> Dns is adguard as its always been set to that and it does it to most sources but seems to only happen at different times of the day hahaha 😆 

Why source you're using? (Uniquestream ,upcloud, vidcloud etc)

**Comment by owencz1998** [comment]
I think it's mostly vidcloud it does it on but sometimes now it doesn't kick me when watching I just get the remote error come up now and then 😩

**Comment by hexated** [comment]
> I think it's mostly vidcloud it does it on but sometimes now it doesn't kick me when watching I just get the remote error come up now and then 😩

What about now, it shouldnt buffer

**Comment by owencz1998** [comment]
So far so good it was mostly when I was watching Friday night dinner when I had the issues sometimes when starting a program it would so remote error but at least its not kicking me off if I have the issue again I'll let u know mate 👌

**Comment by hexated** [comment]
I'll close this now. Feel free to open it again
