### ISSUE TITLE
New Providers [Site Request]

### ISSUE THREAD

**Issue by NoName3045** [hexated/cloudstream-extensions-hexated#66]
Hi, please add these Ukrainian sites if possible
- https://eneyida.tv/
- https://anitube.in.ua/
- https://uaserials.pro/

Thank you!

**Comment by hexated** [comment]
Which one is the best?

**Comment by NoName3045** [comment]
In my opinion, eneyida.tv is the best.

**Comment by CakesTwix** [comment]
@NoName3045, https://raw.githubusercontent.com/CakesTwix/cloudstream-extensions-uk/master/repo.json
UAKino and Eneyida

**Comment by hexated** [comment]
> @NoName3045, https://raw.githubusercontent.com/CakesTwix/cloudstream-extensions-uk/master/repo.json
> UAKino and Eneyida

You can take over this, i'll close this now
