### ISSUE TITLE
Website request and help regarding extension 

### ISSUE THREAD

**Issue by ChandanKSDeveloper** [hexated/cloudstream-extensions-hexated#668]
Can you add this sites:- 
1. [Toonstream](https://toonstream.net/)
2. [Netfilm](https://netfilm.app/)

----------------------------------------------------------
Can you tell me how can I start making my own extensions. Any course or YouTube playlist to learn web scrapping for this. 

And I develop an extension python instead of kotlin, will it work on Android??

**Comment by SaurabhKaperwan** [comment]
No you can't make an extension using python in this app

**Comment by IndusAryan** [comment]
do you understand or not, i told everything that is needed , spamming in different repo wont convert kotlin to snake

![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/125901294/0596a63e-fc14-4fdb-86df-af8be05ad916)

**Comment by ChandanKSDeveloper** [comment]
Ok
