### ISSUE TITLE
Anime dekho and Anplay no links found

### ISSUE THREAD

**Issue by ghost** [hexated/cloudstream-extensions-hexated#699]
The plugin's search and homepage are fully functional. Everything loads properly. But when trying to play anything on AnPlay or Anime Dekho, it instantly says 'No links found'
Users are unable to use the plugin

**Comment by dewxo** [comment]
Yes, please.
I'm waiting for about two weeks for it to be fixed, but it is still broken.
Highlight it please.
Also, I think that AnPlay will not break the much AnimeDekho does, but animedekho has more content.

**Comment by dewxo** [comment]
I think the server url chnaged in case of AnimeDekho, old: `https://vidxstream.xyz` new: `https://vidstreamnew.xyz/`, I am a scraper myself, I could have checked the extension but I don't know how to build and test it on cloudstream.

![image](https://github.com/hexated/cloudstream-extensions-hexated/assets/157586672/7b208d1b-8d4d-4af8-aa40-3ef76c33b366)


@hexated @IndusAryan  If you can provide some sources to get it easy peasy I might contribute soon.

**Comment by IndusAryan** [comment]
this repo is discontinued and unmaintained, hexated left an i dont have write access, but the above 2 extensions can be found in phisher98 repo

**Comment by dewxo** [comment]
I'm feeling bad that it's off now, I hope things get fixed soon

**Comment by IndusAryan** [comment]
well, all of you , i dont think hexated will come, neither i am able to estabilish contact with him.
Dewxo and Rinki Ji, i would suggest using phisher98 extension

**Comment by devvratmiglani** [comment]
Yes, I'm already using it, thanks I just found out you are not a pot but full tank of knowledge, source discord! 😉😺😺

Yeah, I'm dewxo

**Comment by IndusAryan** [comment]
who are you on discord, hit me in dev chat to know connection with me and dev vrat / bhishma !

**Comment by devvratmiglani** [comment]
I'm DewRatDeRossum (DewRat) and Indeed my name is based on Bhishma😉😺

**Comment by Badal771** [comment]
@IndusAryan  can you tell me how can i use phisher 98 repository in my CloudStream Android application ?

**Comment by IndusAryan** [comment]
join plugins server and type !repo
https://discord.gg/Pcv5VsFV

**Comment by Badal771** [comment]
@IndusAryan  i have joined plugin server but i am not able to add repository in my CloudStream Android Application 
Please can you tell me ?

**Comment by Badal771** [comment]
@IndusAryan  I have joined the server but i don't see any hindi repository can you tell me if there is a Hindi Anime Repository ?

**Comment by Rinki-Goyal** [comment]
There is one
