### ISSUE TITLE
HDrezka bug

### ISSUE THREAD

**Issue by NoName3045** [hexated/cloudstream-extensions-hexated#76]
![Screenshot](https://user-images.githubusercontent.com/122519223/213645832-547df210-31ca-44e8-8e35-cd49b4792c9e.jpg)
The unnecessary element "null" is displayed. Please fix this bug. Thank you!

**Comment by hexated** [comment]
> ![Screenshot](https://user-images.githubusercontent.com/122519223/213645832-547df210-31ca-44e8-8e35-cd49b4792c9e.jpg)
> The unnecessary element "null" is displayed. Please fix this bug. Thank you!

What movie?

**Comment by NoName3045** [comment]
> 

[Shrek](https://rezka.ag/cartoons/fantasy/1019-shrek-2001.html)
