### ISSUE TITLE
SORASTREAM

### ISSUE THREAD

**Issue by GlennQu** [hexated/cloudstream-extensions-hexated#77]
I'm using SORASTREAM, how can I remove other sources of SORASTREAM ? so that If I want to play a movie, it will directly go to sorastream instead of xmovie for example. Please Help.

**Comment by hexated** [comment]
> I'm using SORASTREAM, how can I remove other sources of SORASTREAM ? so that If I want to play a movie, it will directly go to sorastream instead of xmovie for example. Please Help. 

You can't remove source, but if you only need "sorastream" source, you can just use loklok. It basically the same
