### ISSUE TITLE
Anilibria bug

### ISSUE THREAD

**Issue by NoName3045** [hexated/cloudstream-extensions-hexated#79]
Posters are not displayed when searching.
![Screenshot](https://user-images.githubusercontent.com/122519223/213915079-c78b159a-b73a-4f62-9ff8-6438af590606.jpg)
Thank you!

**Comment by hexated** [comment]
> Posters are not displayed when searching.
> ![Screenshot](https://user-images.githubusercontent.com/122519223/213915079-c78b159a-b73a-4f62-9ff8-6438af590606.jpg)
> Thank you!

Because website doesnt have it
![Screenshot_20230122-204742.png](https://user-images.githubusercontent.com/37908684/213919219-859c9fa1-a365-416e-9857-e1c6f5377f86.png)
