### ISSUE TITLE
Site Request HuraWatch (Multi)

### ISSUE THREAD

**Issue by MuhaGX** [hexated/cloudstream-extensions-hexated#80]
https://hurawatch.at/home

**Comment by hexated** [comment]
Sflix clone
![Screenshot_20230123-195838.png](https://user-images.githubusercontent.com/37908684/214045719-10b6c048-fe37-4f9e-ae21-60e96137fc55.png)

**Comment by MuhaGX** [comment]
on hurawatch there are lots of subtitles

**Comment by MuhaGX** [comment]
![IMG_20230125_131331](https://user-images.githubusercontent.com/70599137/214493610-b51d9223-8c3d-469e-ab12-b45ad93e9a5d.jpg)
![IMG_20230125_123534](https://user-images.githubusercontent.com/70599137/214493624-6c85e68b-f31e-4477-bd6c-1584faa7fe13.jpg)
