### ISSUE TITLE
[Site Request] HuraWatch 

### ISSUE THREAD

**Issue by MuhaGX** [hexated/cloudstream-extensions-hexated#83]
hurawatch has many subtitles
![image](https://user-images.githubusercontent.com/70599137/214542089-cb9840aa-e61a-4532-b69e-f4b2ff6d61cb.png)
![image](https://user-images.githubusercontent.com/70599137/214542097-4a00f755-2421-40bc-ade6-d139b2b8f3e9.png)

**Comment by hexated** [comment]
This is sflix clone, you can find that in English repo

**Comment by MuhaGX** [comment]
> This is sflix clone, you can find that in English repo

there are no indonesian subtitles on sflix

**Comment by MuhaGX** [comment]
is it difficult to make an extension?
