### ISSUE TITLE
Loklok

### ISSUE THREAD

**Issue by Nebula6531** [hexated/cloudstream-extensions-hexated#9]
Tried with a vpn and all the various DNS's comes up with an error as shown in the screenshot

![Screenshot_20220923-153447_CloudStream Beta](https://user-images.githubusercontent.com/79540507/191985427-6c2e6db8-831e-45d0-976b-0c441adbe240.jpg)

**Comment by hexated** [comment]
What country did you tested?
Try south korea, canada or country in ASIA, it'll work
