### ISSUE TITLE
**{Site Request}** SkymoviesHd

### ISSUE THREAD

**Issue by IbrahimKhan2004** [hexated/cloudstream-extensions-hexated#94]
**Please add SkyMoviesHD to the extension if possible. SkyMoviesHD provides high-quality movies and combined series, and it is my request to include it in the extension.**

**Comment by hexated** [comment]
> **Please add SkyMoviesHD to the extension if possible. SkyMoviesHD provides high-quality movies and combined series, and it is my request to include it in the extension.**

Link?

**Comment by IbrahimKhan2004** [comment]
https://skymovieshd.lat here is the link
