### ISSUE TITLE
XCINE/IO missing episodes.

### ISSUE THREAD

**Issue by Twistee** [hexated/cloudstream-extensions-hexated#99]
If i try to open a TV Show on Xcine most of the episodes are missing and not listed. I think it may be due to the providers. Can u somehow fix that?

**Comment by hexated** [comment]
> If i try to open a TV Show on Xcine most of the episodes are missing and not listed. I think it may be due to the providers. Can u somehow fix that?

Need details. Compare it with website

**Comment by hexated** [comment]
Seems like no issue, i'll close this. Feel free to open it again
